# coding: utf-8

"""
    Nncof_EventsSubscriptionNotification (Callback Receiver)

    Callback receiver specification for the Nncof_EventsSubscription service.  This spec is consumed by PCF/RICF (the NF service consumer) that subscribes to NCOF events. The consumer must implement an HTTP server that exposes the endpoint defined here so that NCOF can deliver notifications to it.  It is intentionally extracted from `Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml` because OpenAPI Generator does not generate server stubs for the `callbacks:` section of an OpenAPI document. Generating from this standalone spec yields a ready-to-implement FastAPI server stub on the consumer side.  Schema simplifications applied for code-generator compatibility (the original `Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml` is unchanged):   - `oneOf` constraints are dropped (validation deferred to business logic).   - 3GPP forward-compatible enum pattern (`anyOf: [enum-string, free-string]`)     is flattened to plain `type: string`.   - All cross-file `$ref`s are inlined into this single document.  6G-I2P ETRI-MoDuTec PoC Scenario. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from nncof_cb.models.ellipsoid_arc import EllipsoidArc
from nncof_cb.models.point import Point
from nncof_cb.models.point_altitude import PointAltitude
from nncof_cb.models.point_altitude_uncertainty import PointAltitudeUncertainty
from nncof_cb.models.point_uncertainty_circle import PointUncertaintyCircle
from nncof_cb.models.point_uncertainty_ellipse import PointUncertaintyEllipse
from nncof_cb.models.polygon import Polygon
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

GEOGRAPHICAREA_ANY_OF_SCHEMAS = ["EllipsoidArc", "Point", "PointAltitude", "PointAltitudeUncertainty", "PointUncertaintyCircle", "PointUncertaintyEllipse", "Polygon"]

class GeographicArea(BaseModel):
    """
    Geographic area specified by different shape.
    """

    # data type: Point
    anyof_schema_1_validator: Optional[Point] = None
    # data type: PointUncertaintyCircle
    anyof_schema_2_validator: Optional[PointUncertaintyCircle] = None
    # data type: PointUncertaintyEllipse
    anyof_schema_3_validator: Optional[PointUncertaintyEllipse] = None
    # data type: Polygon
    anyof_schema_4_validator: Optional[Polygon] = None
    # data type: PointAltitude
    anyof_schema_5_validator: Optional[PointAltitude] = None
    # data type: PointAltitudeUncertainty
    anyof_schema_6_validator: Optional[PointAltitudeUncertainty] = None
    # data type: EllipsoidArc
    anyof_schema_7_validator: Optional[EllipsoidArc] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[EllipsoidArc, Point, PointAltitude, PointAltitudeUncertainty, PointUncertaintyCircle, PointUncertaintyEllipse, Polygon]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: List[str] = Literal[GEOGRAPHICAREA_ANY_OF_SCHEMAS]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = GeographicArea.model_construct()
        error_messages = []
        # validate data type: Point
        if not isinstance(v, Point):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Point`")
        else:
            return v

        # validate data type: PointUncertaintyCircle
        if not isinstance(v, PointUncertaintyCircle):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PointUncertaintyCircle`")
        else:
            return v

        # validate data type: PointUncertaintyEllipse
        if not isinstance(v, PointUncertaintyEllipse):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PointUncertaintyEllipse`")
        else:
            return v

        # validate data type: Polygon
        if not isinstance(v, Polygon):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Polygon`")
        else:
            return v

        # validate data type: PointAltitude
        if not isinstance(v, PointAltitude):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PointAltitude`")
        else:
            return v

        # validate data type: PointAltitudeUncertainty
        if not isinstance(v, PointAltitudeUncertainty):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PointAltitudeUncertainty`")
        else:
            return v

        # validate data type: EllipsoidArc
        if not isinstance(v, EllipsoidArc):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EllipsoidArc`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in GeographicArea with anyOf schemas: EllipsoidArc, Point, PointAltitude, PointAltitudeUncertainty, PointUncertaintyCircle, PointUncertaintyEllipse, Polygon. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[Point] = None
        try:
            instance.actual_instance = Point.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[PointUncertaintyCircle] = None
        try:
            instance.actual_instance = PointUncertaintyCircle.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[PointUncertaintyEllipse] = None
        try:
            instance.actual_instance = PointUncertaintyEllipse.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[Polygon] = None
        try:
            instance.actual_instance = Polygon.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[PointAltitude] = None
        try:
            instance.actual_instance = PointAltitude.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_6_validator: Optional[PointAltitudeUncertainty] = None
        try:
            instance.actual_instance = PointAltitudeUncertainty.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_7_validator: Optional[EllipsoidArc] = None
        try:
            instance.actual_instance = EllipsoidArc.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into GeographicArea with anyOf schemas: EllipsoidArc, Point, PointAltitude, PointAltitudeUncertainty, PointUncertaintyCircle, PointUncertaintyEllipse, Polygon. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


