# coding: utf-8

"""
    Nncof_EventsSubscriptionNotification (Callback Receiver)

    Callback receiver specification for the Nncof_EventsSubscription service.  This spec is consumed by PCF/RICF (the NF service consumer) that subscribes to NCOF events. The consumer must implement an HTTP server that exposes the endpoint defined here so that NCOF can deliver notifications to it.  It is intentionally extracted from `Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml` because OpenAPI Generator does not generate server stubs for the `callbacks:` section of an OpenAPI document. Generating from this standalone spec yields a ready-to-implement FastAPI server stub on the consumer side.  Schema simplifications applied for code-generator compatibility (the original `Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml` is unchanged):   - `oneOf` constraints are dropped (validation deferred to business logic).   - 3GPP forward-compatible enum pattern (`anyOf: [enum-string, free-string]`)     is flattened to plain `type: string`.   - All cross-file `$ref`s are inlined into this single document.  6G-I2P ETRI-MoDuTec PoC Scenario. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nncof_cb.models.geo_distribution_info import GeoDistributionInfo
from nncof_cb.models.geographical_area import GeographicalArea
from nncof_cb.models.user_location import UserLocation
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class LocationInfo(BaseModel):
    """
    Represents UE location information.
    """ # noqa: E501
    loc: UserLocation
    geo_loc: Optional[GeographicalArea] = Field(default=None, alias="geoLoc")
    ratio: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=None, description="Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.  ")
    confidence: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.")
    geo_distr_infos: Optional[Annotated[List[GeoDistributionInfo], Field(min_length=1)]] = Field(default=None, alias="geoDistrInfos")
    dist_threshold: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.", alias="distThreshold")
    __properties: ClassVar[List[str]] = ["loc", "geoLoc", "ratio", "confidence", "geoDistrInfos", "distThreshold"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LocationInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of loc
        if self.loc:
            _dict['loc'] = self.loc.to_dict()
        # override the default output from pydantic by calling `to_dict()` of geo_loc
        if self.geo_loc:
            _dict['geoLoc'] = self.geo_loc.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in geo_distr_infos (list)
        _items = []
        if self.geo_distr_infos:
            for _item in self.geo_distr_infos:
                if _item:
                    _items.append(_item.to_dict())
            _dict['geoDistrInfos'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of LocationInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "loc": UserLocation.from_dict(obj.get("loc")) if obj.get("loc") is not None else None,
            "geoLoc": GeographicalArea.from_dict(obj.get("geoLoc")) if obj.get("geoLoc") is not None else None,
            "ratio": obj.get("ratio"),
            "confidence": obj.get("confidence"),
            "geoDistrInfos": [GeoDistributionInfo.from_dict(_item) for _item in obj.get("geoDistrInfos")] if obj.get("geoDistrInfos") is not None else None,
            "distThreshold": obj.get("distThreshold")
        })
        return _obj


