# coding: utf-8

"""
    Nncof_EventsSubscriptionNotification (Callback Receiver)

    Callback receiver specification for the Nncof_EventsSubscription service.  This spec is consumed by PCF/RICF (the NF service consumer) that subscribes to NCOF events. The consumer must implement an HTTP server that exposes the endpoint defined here so that NCOF can deliver notifications to it.  It is intentionally extracted from `Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml` because OpenAPI Generator does not generate server stubs for the `callbacks:` section of an OpenAPI document. Generating from this standalone spec yields a ready-to-implement FastAPI server stub on the consumer side.  Schema simplifications applied for code-generator compatibility (the original `Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml` is unchanged):   - `oneOf` constraints are dropped (validation deferred to business logic).   - 3GPP forward-compatible enum pattern (`anyOf: [enum-string, free-string]`)     is flattened to plain `type: string`.   - All cross-file `$ref`s are inlined into this single document.  6G-I2P ETRI-MoDuTec PoC Scenario. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nncof_cb.models.traffic_information import TrafficInformation
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WlanPerTsPerformanceInfo(BaseModel):
    """
    WLAN performance information per Time Slot during the analytics target period.
    """ # noqa: E501
    ts_start: datetime = Field(description="string with format \"date-time\" as defined in OpenAPI.", alias="tsStart")
    ts_duration: StrictInt = Field(description="indicating a time in seconds.", alias="tsDuration")
    rssi: Optional[StrictInt] = None
    rtt: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.")
    traffic_info: Optional[TrafficInformation] = Field(default=None, alias="trafficInfo")
    number_of_ues: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.", alias="numberOfUes")
    confidence: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.")
    __properties: ClassVar[List[str]] = ["tsStart", "tsDuration", "rssi", "rtt", "trafficInfo", "numberOfUes", "confidence"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WlanPerTsPerformanceInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of traffic_info
        if self.traffic_info:
            _dict['trafficInfo'] = self.traffic_info.to_dict()
        # set to None if traffic_info (nullable) is None
        # and model_fields_set contains the field
        if self.traffic_info is None and "traffic_info" in self.model_fields_set:
            _dict['trafficInfo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WlanPerTsPerformanceInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tsStart": obj.get("tsStart"),
            "tsDuration": obj.get("tsDuration"),
            "rssi": obj.get("rssi"),
            "rtt": obj.get("rtt"),
            "trafficInfo": TrafficInformation.from_dict(obj.get("trafficInfo")) if obj.get("trafficInfo") is not None else None,
            "numberOfUes": obj.get("numberOfUes"),
            "confidence": obj.get("confidence")
        })
        return _obj


