# coding: utf-8

from typing import ClassVar, Dict, List, Tuple  # noqa: F401

from typing import Any
from nupf_cb.models.notification_data import NotificationData
from nupf_cb.models.problem_details import ProblemDetails
from nupf_cb.models.redirect_response import RedirectResponse
from nupf_cb.security_api import get_token_oAuth2ClientCredentials

class BaseUPFEventExposureNotificationCallbackReceiverApi:
    subclasses: ClassVar[Tuple] = ()

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        BaseUPFEventExposureNotificationCallbackReceiverApi.subclasses = BaseUPFEventExposureNotificationCallbackReceiverApi.subclasses + (cls,)
    async def receive_upf_event_notification(
        self,
        body: NotificationData,
    ) -> None:
        """Endpoint that the NF service consumer implements to receive Notifications generated by the producer NF. The producer calls this endpoint using the URI registered as the notification URI at subscription creation time."""
        ...
