# coding: utf-8

"""
Nsmf_EventExposure

Session Management Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

The version of the OpenAPI document: 1.4.0-alpha.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import asyncio
from contextlib import asynccontextmanager

from fastapi import FastAPI

from nsmf.apis.individual_subscription_document_api import (
    router as IndividualSubscriptionDocumentApiRouter,
)
from nsmf.apis.subscriptions_collection_api import (
    router as SubscriptionsCollectionApiRouter,
)

from nsmf.impl import utils
from nsmf.impl.simulation import start_dl_throughput_toggle


@asynccontextmanager
async def lifespan(app: FastAPI):
    asyncio.create_task(start_dl_throughput_toggle(interval_seconds=6))
    yield


app = FastAPI(
    title="Nsmf_EventExposure",
    description="Session Management Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. ",
    version="1.4.0-alpha.4",
    lifespan=lifespan,
)

app.include_router(IndividualSubscriptionDocumentApiRouter)
app.include_router(SubscriptionsCollectionApiRouter)

utils.print_logo()
