# coding: utf-8

from typing import ClassVar, Dict, List, Tuple  # noqa: F401

from pydantic import Field
from typing import Any, List
from typing_extensions import Annotated
from nncof_cb.models.nncof_events_subscription_notification import (
    NncofEventsSubscriptionNotification,
)
from nncof_cb.models.problem_details import ProblemDetails
from nncof_cb.models.redirect_response import RedirectResponse
from nncof_cb.security_api import get_token_oAuth2ClientCredentials


class BaseNCOFEventsSubscriptionNotificationCallbackReceiverApi:
    subclasses: ClassVar[Tuple] = ()

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        BaseNCOFEventsSubscriptionNotificationCallbackReceiverApi.subclasses = (
            BaseNCOFEventsSubscriptionNotificationCallbackReceiverApi.subclasses
            + (cls,)
        )

    async def receive_ncof_events_subscription_notification(
        self,
        type: str,
        nncof_events_subscription_notification: Annotated[
            List[NncofEventsSubscriptionNotification],
            Field(min_length=1),
        ],
    ) -> None:
        """Endpoint that the NF service consumer implements to receive Notifications generated by the producer NF. The producer calls this endpoint using the URI registered as the notification URI at subscription creation time."""
        ...
