# coding: utf-8

from typing import ClassVar, Dict, List, Tuple  # noqa: F401

from typing import Any
from nnef_cb.models.nef_event_exposure_notif import NefEventExposureNotif
from nnef_cb.models.problem_details import ProblemDetails
from nnef_cb.models.redirect_response import RedirectResponse
from nnef_cb.security_api import get_token_oAuth2ClientCredentials

class BaseNEFEventExposureNotificationCallbackReceiverApi:
    subclasses: ClassVar[Tuple] = ()

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        BaseNEFEventExposureNotificationCallbackReceiverApi.subclasses = BaseNEFEventExposureNotificationCallbackReceiverApi.subclasses + (cls,)
    async def receive_nef_event_exposure_notif(
        self,
        nef_event_exposure_notif: NefEventExposureNotif,
    ) -> None:
        """Endpoint that the NF service consumer implements to receive Notifications generated by the producer NF. The producer calls this endpoint using the URI registered as the notification URI at subscription creation time."""
        ...
