# coding: utf-8

"""
    UPF Event Exposure Service

    UPF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.2.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nupf.models.flow_direction import FlowDirection
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EthFlowDescription(BaseModel):
    """
    Identifies an Ethernet flow.
    """ # noqa: E501
    dest_mac_addr: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042. ", alias="destMacAddr")
    eth_type: StrictStr = Field(alias="ethType")
    f_desc: Optional[StrictStr] = Field(default=None, description="Defines a packet filter of an IP flow.", alias="fDesc")
    f_dir: Optional[FlowDirection] = Field(default=None, alias="fDir")
    source_mac_addr: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042. ", alias="sourceMacAddr")
    vlan_tags: Optional[Annotated[List[StrictStr], Field(min_length=1, max_length=2)]] = Field(default=None, alias="vlanTags")
    src_mac_addr_end: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042. ", alias="srcMacAddrEnd")
    dest_mac_addr_end: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042. ", alias="destMacAddrEnd")
    __properties: ClassVar[List[str]] = ["destMacAddr", "ethType", "fDesc", "fDir", "sourceMacAddr", "vlanTags", "srcMacAddrEnd", "destMacAddrEnd"]

    @field_validator('dest_mac_addr')
    def dest_mac_addr_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$", value):
            raise ValueError(r"must validate the regular expression /^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$/")
        return value

    @field_validator('source_mac_addr')
    def source_mac_addr_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$", value):
            raise ValueError(r"must validate the regular expression /^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$/")
        return value

    @field_validator('src_mac_addr_end')
    def src_mac_addr_end_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$", value):
            raise ValueError(r"must validate the regular expression /^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$/")
        return value

    @field_validator('dest_mac_addr_end')
    def dest_mac_addr_end_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$", value):
            raise ValueError(r"must validate the regular expression /^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EthFlowDescription from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of f_dir
        if self.f_dir:
            _dict['fDir'] = self.f_dir.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EthFlowDescription from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "destMacAddr": obj.get("destMacAddr"),
            "ethType": obj.get("ethType"),
            "fDesc": obj.get("fDesc"),
            "fDir": FlowDirection.from_dict(obj.get("fDir")) if obj.get("fDir") is not None else None,
            "sourceMacAddr": obj.get("sourceMacAddr"),
            "vlanTags": obj.get("vlanTags"),
            "srcMacAddrEnd": obj.get("srcMacAddrEnd"),
            "destMacAddrEnd": obj.get("destMacAddrEnd")
        })
        return _obj


