# coding: utf-8

"""
    UPF Event Exposure Service

    UPF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.2.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nupf.models.ipv6_addr import Ipv6Addr
from nupf.models.transport_protocol import TransportProtocol
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NatMapping(BaseModel):
    """
    NAT Mapping
    """ # noqa: E501
    ipv4_addr: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166. ", alias="ipv4Addr")
    ipv6_addr: Optional[Ipv6Addr] = Field(default=None, alias="ipv6Addr")
    port_number: Annotated[int, Field(le=65535, strict=True, ge=0)] = Field(description="Integer where the allowed values correspond to the value range of an unsigned 16-bit integer. ", alias="portNumber")
    transport_protocol: Optional[TransportProtocol] = Field(default=None, alias="transportProtocol")
    remote_port_number: Optional[Annotated[int, Field(le=65535, strict=True, ge=0)]] = Field(default=None, description="Integer where the allowed values correspond to the value range of an unsigned 16-bit integer. ", alias="remotePortNumber")
    __properties: ClassVar[List[str]] = ["ipv4Addr", "ipv6Addr", "portNumber", "transportProtocol", "remotePortNumber"]

    @field_validator('ipv4_addr')
    def ipv4_addr_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$", value):
            raise ValueError(r"must validate the regular expression /^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NatMapping from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ipv6_addr
        if self.ipv6_addr:
            _dict['ipv6Addr'] = self.ipv6_addr.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transport_protocol
        if self.transport_protocol:
            _dict['transportProtocol'] = self.transport_protocol.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NatMapping from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ipv4Addr": obj.get("ipv4Addr"),
            "ipv6Addr": Ipv6Addr.from_dict(obj.get("ipv6Addr")) if obj.get("ipv6Addr") is not None else None,
            "portNumber": obj.get("portNumber"),
            "transportProtocol": TransportProtocol.from_dict(obj.get("transportProtocol")) if obj.get("transportProtocol") is not None else None,
            "remotePortNumber": obj.get("remotePortNumber")
        })
        return _obj


