# coding: utf-8

"""
    UPF Event Exposure Service

    UPF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.2.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nupf.models.notification_item import NotificationItem
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NotificationData(BaseModel):
    """
    the list of NotificationItems
    """ # noqa: E501
    notification_items: Annotated[List[Optional[NotificationItem]], Field(min_length=1)] = Field(alias="notificationItems")
    correlation_id: Optional[StrictStr] = Field(default=None, alias="correlationId")
    achieved_samp_ratio: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=None, description="Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.  ", alias="achievedSampRatio")
    event_notify_uri: Optional[StrictStr] = Field(default=None, description="String providing an URI formatted according to RFC 3986.", alias="eventNotifyUri")
    __properties: ClassVar[List[str]] = ["notificationItems", "correlationId", "achievedSampRatio", "eventNotifyUri"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NotificationData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in notification_items (list)
        _items = []
        if self.notification_items:
            for _item in self.notification_items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['notificationItems'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NotificationData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "notificationItems": [NotificationItem.from_dict(_item) for _item in obj.get("notificationItems")] if obj.get("notificationItems") is not None else None,
            "correlationId": obj.get("correlationId"),
            "achievedSampRatio": obj.get("achievedSampRatio"),
            "eventNotifyUri": obj.get("eventNotifyUri")
        })
        return _obj


