# coding: utf-8

"""
    UPF Event Exposure Service

    UPF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.2.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nupf.models.ip_addr import IpAddr
from nupf.models.snssai import Snssai
from nupf.models.upf_event import UpfEvent
from nupf.models.upf_event_mode import UpfEventMode
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UpfEventSubscription(BaseModel):
    """
    UPF Event Subscription
    """ # noqa: E501
    event_list: Annotated[List[UpfEvent], Field(min_length=1)] = Field(alias="eventList")
    event_notify_uri: StrictStr = Field(description="String providing an URI formatted according to RFC 3986.", alias="eventNotifyUri")
    notify_correlation_id: StrictStr = Field(alias="notifyCorrelationId")
    event_reporting_mode: UpfEventMode = Field(alias="eventReportingMode")
    nf_id: StrictStr = Field(description="String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4.  ", alias="nfId")
    ue_ip_address: Optional[IpAddr] = Field(default=None, alias="ueIpAddress")
    any_ue: Optional[StrictBool] = Field(default=False, alias="anyUe")
    supi: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \"lower-with-hyphen\" naming convention    defined in 3GPP TS 29.501. ")
    dnn: Optional[StrictStr] = Field(default=None, description="String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \"Label1.Label2.Label3\"). ")
    snssai: Optional[Snssai] = None
    bundling_allowed: Optional[StrictBool] = Field(default=None, alias="bundlingAllowed")
    bundle_id: Optional[Annotated[int, Field(le=4294967295, strict=True, ge=0)]] = Field(default=None, description="Integer where the allowed values correspond to the value range of an unsigned 32-bit integer. ", alias="bundleId")
    bundled_event_notify_uri: Optional[StrictStr] = Field(default=None, description="String providing an URI formatted according to RFC 3986.", alias="bundledEventNotifyUri")
    __properties: ClassVar[List[str]] = ["eventList", "eventNotifyUri", "notifyCorrelationId", "eventReportingMode", "nfId", "ueIpAddress", "anyUe", "supi", "dnn", "snssai", "bundlingAllowed", "bundleId", "bundledEventNotifyUri"]

    @field_validator('supi')
    def supi_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(imsi-[0-9]{5,15}|nai-.+|gci-.+|gli-.+|.+)$", value):
            raise ValueError(r"must validate the regular expression /^(imsi-[0-9]{5,15}|nai-.+|gci-.+|gli-.+|.+)$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UpfEventSubscription from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in event_list (list)
        _items = []
        if self.event_list:
            for _item in self.event_list:
                if _item:
                    _items.append(_item.to_dict())
            _dict['eventList'] = _items
        # override the default output from pydantic by calling `to_dict()` of event_reporting_mode
        if self.event_reporting_mode:
            _dict['eventReportingMode'] = self.event_reporting_mode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ue_ip_address
        if self.ue_ip_address:
            _dict['ueIpAddress'] = self.ue_ip_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of snssai
        if self.snssai:
            _dict['snssai'] = self.snssai.to_dict()
        # set to None if ue_ip_address (nullable) is None
        # and model_fields_set contains the field
        if self.ue_ip_address is None and "ue_ip_address" in self.model_fields_set:
            _dict['ueIpAddress'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UpfEventSubscription from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "eventList": [UpfEvent.from_dict(_item) for _item in obj.get("eventList")] if obj.get("eventList") is not None else None,
            "eventNotifyUri": obj.get("eventNotifyUri"),
            "notifyCorrelationId": obj.get("notifyCorrelationId"),
            "eventReportingMode": UpfEventMode.from_dict(obj.get("eventReportingMode")) if obj.get("eventReportingMode") is not None else None,
            "nfId": obj.get("nfId"),
            "ueIpAddress": IpAddr.from_dict(obj.get("ueIpAddress")) if obj.get("ueIpAddress") is not None else None,
            "anyUe": obj.get("anyUe") if obj.get("anyUe") is not None else False,
            "supi": obj.get("supi"),
            "dnn": obj.get("dnn"),
            "snssai": Snssai.from_dict(obj.get("snssai")) if obj.get("snssai") is not None else None,
            "bundlingAllowed": obj.get("bundlingAllowed"),
            "bundleId": obj.get("bundleId"),
            "bundledEventNotifyUri": obj.get("bundledEventNotifyUri")
        })
        return _obj


