# coding: utf-8

"""
    UPF Event Exposure Service

    UPF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.2.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from nupf.models.application_related_information import ApplicationRelatedInformation
from nupf.models.flow_information import FlowInformation
from nupf.models.throughput_measurement import ThroughputMeasurement
from nupf.models.throughput_statistics_measurement import ThroughputStatisticsMeasurement
from nupf.models.volume_measurement import VolumeMeasurement
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UserDataUsageMeasurements(BaseModel):
    """
    User Data Usage Measurements either for the PDU session, or the app-id, or the data flow 
    """ # noqa: E501
    app_id: Optional[StrictStr] = Field(default=None, description="String providing an application identifier.", alias="appId")
    flow_info: Optional[FlowInformation] = Field(default=None, alias="flowInfo")
    volume_measurement: Optional[VolumeMeasurement] = Field(default=None, alias="volumeMeasurement")
    throughput_measurement: Optional[ThroughputMeasurement] = Field(default=None, alias="throughputMeasurement")
    application_related_information: Optional[ApplicationRelatedInformation] = Field(default=None, alias="applicationRelatedInformation")
    throughput_statistics_measurement: Optional[ThroughputStatisticsMeasurement] = Field(default=None, alias="throughputStatisticsMeasurement")
    __properties: ClassVar[List[str]] = ["appId", "flowInfo", "volumeMeasurement", "throughputMeasurement", "applicationRelatedInformation", "throughputStatisticsMeasurement"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserDataUsageMeasurements from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of flow_info
        if self.flow_info:
            _dict['flowInfo'] = self.flow_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of volume_measurement
        if self.volume_measurement:
            _dict['volumeMeasurement'] = self.volume_measurement.to_dict()
        # override the default output from pydantic by calling `to_dict()` of throughput_measurement
        if self.throughput_measurement:
            _dict['throughputMeasurement'] = self.throughput_measurement.to_dict()
        # override the default output from pydantic by calling `to_dict()` of application_related_information
        if self.application_related_information:
            _dict['applicationRelatedInformation'] = self.application_related_information.to_dict()
        # override the default output from pydantic by calling `to_dict()` of throughput_statistics_measurement
        if self.throughput_statistics_measurement:
            _dict['throughputStatisticsMeasurement'] = self.throughput_statistics_measurement.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UserDataUsageMeasurements from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "appId": obj.get("appId"),
            "flowInfo": FlowInformation.from_dict(obj.get("flowInfo")) if obj.get("flowInfo") is not None else None,
            "volumeMeasurement": VolumeMeasurement.from_dict(obj.get("volumeMeasurement")) if obj.get("volumeMeasurement") is not None else None,
            "throughputMeasurement": ThroughputMeasurement.from_dict(obj.get("throughputMeasurement")) if obj.get("throughputMeasurement") is not None else None,
            "applicationRelatedInformation": ApplicationRelatedInformation.from_dict(obj.get("applicationRelatedInformation")) if obj.get("applicationRelatedInformation") is not None else None,
            "throughputStatisticsMeasurement": ThroughputStatisticsMeasurement.from_dict(obj.get("throughputStatisticsMeasurement")) if obj.get("throughputStatisticsMeasurement") is not None else None
        })
        return _obj


