# coding: utf-8

"""
    Nupf_EventExposure Notification (Callback Receiver)

    Callback receiver specification for the Nupf_EventExposure service.  This spec is consumed by NCOF (the NF service consumer) that subscribes to UPF events. The consumer must implement an HTTP server that exposes the endpoint defined here so that UPF can deliver notifications to it.  It is intentionally extracted from `TS29564_Nupf_EventExposure_PoC_ETRI_DoDo1.yaml` because OpenAPI Generator does not generate server stubs for the `callbacks:` section of an OpenAPI document. Generating from this standalone spec yields a ready-to-implement FastAPI server stub on the consumer side.  Schema simplifications applied for code-generator compatibility (the original `TS29564_Nupf_EventExposure_PoC_ETRI_DoDo1.yaml` is unchanged):   - `oneOf` constraints are dropped (validation deferred to business logic).   - 3GPP forward-compatible enum pattern (`anyOf: [enum-string, free-string]`)     is flattened to plain `type: string`.   - All cross-file `$ref`s are inlined into this single document.  6G-I2P ETRI-MoDuTec PoC Scenario. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class NullValue(, Enum):
    """
    JSON's null value.
    """

    """
    allowed enum values
    """

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NullValue from a JSON string"""
        return cls(json.loads(json_str))


