# coding: utf-8

"""
    Nnef_EventExposure

    NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nnef.models.per_ue_attribute import PerUeAttribute
from nnef.models.ue_trajectory_collection import UeTrajectoryCollection
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CollectiveBehaviourInfo(BaseModel):
    """
    Contains the collective behaviour information to be reported to the subscriber.
    """ # noqa: E501
    col_attrib: Optional[Annotated[List[PerUeAttribute], Field(min_length=1)]] = Field(default=None, alias="colAttrib")
    no_of_ues: Optional[StrictInt] = Field(default=None, description="Total number of UEs that fulfil a collective within the area of interest.", alias="noOfUes")
    app_ids: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, alias="appIds")
    ext_ue_ids: Optional[Annotated[List[Annotated[str, Field(strict=True)]], Field(min_length=1)]] = Field(default=None, alias="extUeIds")
    ue_ids: Optional[Annotated[List[Annotated[str, Field(strict=True)]], Field(min_length=1)]] = Field(default=None, alias="ueIds")
    collision_dist: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.", alias="collisionDist")
    abs_dirs: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, alias="absDirs")
    rel_dirs: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, alias="relDirs")
    ue_trajectory: Optional[UeTrajectoryCollection] = Field(default=None, alias="ueTrajectory")
    confidence: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.")
    __properties: ClassVar[List[str]] = ["colAttrib", "noOfUes", "appIds", "extUeIds", "ueIds", "collisionDist", "absDirs", "relDirs", "ueTrajectory", "confidence"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CollectiveBehaviourInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in col_attrib (list)
        _items = []
        if self.col_attrib:
            for _item in self.col_attrib:
                if _item:
                    _items.append(_item.to_dict())
            _dict['colAttrib'] = _items
        # override the default output from pydantic by calling `to_dict()` of ue_trajectory
        if self.ue_trajectory:
            _dict['ueTrajectory'] = self.ue_trajectory.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CollectiveBehaviourInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "colAttrib": [PerUeAttribute.from_dict(_item) for _item in obj.get("colAttrib")] if obj.get("colAttrib") is not None else None,
            "noOfUes": obj.get("noOfUes"),
            "appIds": obj.get("appIds"),
            "extUeIds": obj.get("extUeIds"),
            "ueIds": obj.get("ueIds"),
            "collisionDist": obj.get("collisionDist"),
            "absDirs": obj.get("absDirs"),
            "relDirs": obj.get("relDirs"),
            "ueTrajectory": UeTrajectoryCollection.from_dict(obj.get("ueTrajectory")) if obj.get("ueTrajectory") is not None else None,
            "confidence": obj.get("confidence")
        })
        return _obj


