# coding: utf-8

"""
    Nnef_EventExposure

    NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from nnef.models.data_aggregation_function_type import DataAggregationFunctionType
from nnef.models.media_streaming_access_event import MediaStreamingAccessEvent
from nnef.models.provisioning_session_type import ProvisioningSessionType
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MediaStreamingAccessesCollection(BaseModel):
    """
    A collection of Media Streaming Access Event records.
    """ # noqa: E501
    collection_timestamp: datetime = Field(description="string with format 'date-time' as defined in OpenAPI.", alias="collectionTimestamp")
    start_timestamp: datetime = Field(description="string with format 'date-time' as defined in OpenAPI.", alias="startTimestamp")
    end_timestamp: datetime = Field(description="string with format 'date-time' as defined in OpenAPI.", alias="endTimestamp")
    sample_count: Annotated[int, Field(strict=True, ge=1)] = Field(description="The number of data samples included in or summarised by this collection.", alias="sampleCount")
    streaming_direction: ProvisioningSessionType = Field(alias="streamingDirection")
    summarisations: Annotated[List[DataAggregationFunctionType], Field(min_length=1)] = Field(description="One or more data aggregation functions that have been applied to the UE data to produce summary records present in this collection.")
    records: Annotated[List[MediaStreamingAccessEvent], Field(min_length=0)] = Field(description="A set of records, each one describing one media streaming access.")
    __properties: ClassVar[List[str]] = ["collectionTimestamp", "startTimestamp", "endTimestamp", "sampleCount", "streamingDirection", "summarisations", "records"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MediaStreamingAccessesCollection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of streaming_direction
        if self.streaming_direction:
            _dict['streamingDirection'] = self.streaming_direction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in summarisations (list)
        _items = []
        if self.summarisations:
            for _item in self.summarisations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['summarisations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in records (list)
        _items = []
        if self.records:
            for _item in self.records:
                if _item:
                    _items.append(_item.to_dict())
            _dict['records'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MediaStreamingAccessesCollection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "collectionTimestamp": obj.get("collectionTimestamp"),
            "startTimestamp": obj.get("startTimestamp"),
            "endTimestamp": obj.get("endTimestamp"),
            "sampleCount": obj.get("sampleCount"),
            "streamingDirection": ProvisioningSessionType.from_dict(obj.get("streamingDirection")) if obj.get("streamingDirection") is not None else None,
            "summarisations": [DataAggregationFunctionType.from_dict(_item) for _item in obj.get("summarisations")] if obj.get("summarisations") is not None else None,
            "records": [MediaStreamingAccessEvent.from_dict(_item) for _item in obj.get("records")] if obj.get("records") is not None else None
        })
        return _obj


