# coding: utf-8

"""
    Nnef_EventExposure

    NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from nnef.models.cache_status import CacheStatus
from nnef.models.endpoint_address import EndpointAddress
from nnef.models.media_streaming_access_connection_metrics import MediaStreamingAccessConnectionMetrics
from nnef.models.media_streaming_access_request_message import MediaStreamingAccessRequestMessage
from nnef.models.media_streaming_access_response_message import MediaStreamingAccessResponseMessage
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MediaStreamingAccess(BaseModel):
    """
    Common properties of a single media access by the Media Stream Handler.
    """ # noqa: E501
    media_stream_handler_endpoint_address: EndpointAddress = Field(alias="mediaStreamHandlerEndpointAddress")
    application_server_endpoint_address: EndpointAddress = Field(alias="applicationServerEndpointAddress")
    request_message: MediaStreamingAccessRequestMessage = Field(alias="requestMessage")
    cache_status: Optional[CacheStatus] = Field(default=None, alias="cacheStatus")
    response_message: MediaStreamingAccessResponseMessage = Field(alias="responseMessage")
    processing_latency: Union[StrictFloat, StrictInt] = Field(description="string with format 'float' as defined in OpenAPI.", alias="processingLatency")
    connection_metrics: Optional[MediaStreamingAccessConnectionMetrics] = Field(default=None, alias="connectionMetrics")
    __properties: ClassVar[List[str]] = ["mediaStreamHandlerEndpointAddress", "applicationServerEndpointAddress", "requestMessage", "cacheStatus", "responseMessage", "processingLatency", "connectionMetrics"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MediaStreamingAccess from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of media_stream_handler_endpoint_address
        if self.media_stream_handler_endpoint_address:
            _dict['mediaStreamHandlerEndpointAddress'] = self.media_stream_handler_endpoint_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of application_server_endpoint_address
        if self.application_server_endpoint_address:
            _dict['applicationServerEndpointAddress'] = self.application_server_endpoint_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of request_message
        if self.request_message:
            _dict['requestMessage'] = self.request_message.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cache_status
        if self.cache_status:
            _dict['cacheStatus'] = self.cache_status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of response_message
        if self.response_message:
            _dict['responseMessage'] = self.response_message.to_dict()
        # override the default output from pydantic by calling `to_dict()` of connection_metrics
        if self.connection_metrics:
            _dict['connectionMetrics'] = self.connection_metrics.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MediaStreamingAccess from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mediaStreamHandlerEndpointAddress": EndpointAddress.from_dict(obj.get("mediaStreamHandlerEndpointAddress")) if obj.get("mediaStreamHandlerEndpointAddress") is not None else None,
            "applicationServerEndpointAddress": EndpointAddress.from_dict(obj.get("applicationServerEndpointAddress")) if obj.get("applicationServerEndpointAddress") is not None else None,
            "requestMessage": MediaStreamingAccessRequestMessage.from_dict(obj.get("requestMessage")) if obj.get("requestMessage") is not None else None,
            "cacheStatus": CacheStatus.from_dict(obj.get("cacheStatus")) if obj.get("cacheStatus") is not None else None,
            "responseMessage": MediaStreamingAccessResponseMessage.from_dict(obj.get("responseMessage")) if obj.get("responseMessage") is not None else None,
            "processingLatency": obj.get("processingLatency"),
            "connectionMetrics": MediaStreamingAccessConnectionMetrics.from_dict(obj.get("connectionMetrics")) if obj.get("connectionMetrics") is not None else None
        })
        return _obj


