# coding: utf-8

"""
    Nnef_EventExposure

    NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nnef.models.nef_event_notification import NefEventNotification
from nnef.models.nef_event_subs import NefEventSubs
from nnef.models.reporting_information import ReportingInformation
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NefEventExposureSubsc(BaseModel):
    """
    Represents an Individual Network Exposure Event Subscription resource.
    """ # noqa: E501
    data_acc_prof_id: Optional[StrictStr] = Field(default=None, alias="dataAccProfId")
    events_subs: Annotated[List[NefEventSubs], Field(min_length=1)] = Field(alias="eventsSubs")
    events_rep_info: Optional[ReportingInformation] = Field(default=None, alias="eventsRepInfo")
    notif_uri: StrictStr = Field(description="String providing an URI formatted according to RFC 3986.", alias="notifUri")
    notif_id: StrictStr = Field(alias="notifId")
    event_notifs: Optional[Annotated[List[NefEventNotification], Field(min_length=1)]] = Field(default=None, alias="eventNotifs")
    supp_feat: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. ", alias="suppFeat")
    __properties: ClassVar[List[str]] = ["dataAccProfId", "eventsSubs", "eventsRepInfo", "notifUri", "notifId", "eventNotifs", "suppFeat"]

    @field_validator('supp_feat')
    def supp_feat_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Fa-f0-9]*$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]*$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NefEventExposureSubsc from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in events_subs (list)
        _items = []
        if self.events_subs:
            for _item in self.events_subs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['eventsSubs'] = _items
        # override the default output from pydantic by calling `to_dict()` of events_rep_info
        if self.events_rep_info:
            _dict['eventsRepInfo'] = self.events_rep_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in event_notifs (list)
        _items = []
        if self.event_notifs:
            for _item in self.event_notifs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['eventNotifs'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NefEventExposureSubsc from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dataAccProfId": obj.get("dataAccProfId"),
            "eventsSubs": [NefEventSubs.from_dict(_item) for _item in obj.get("eventsSubs")] if obj.get("eventsSubs") is not None else None,
            "eventsRepInfo": ReportingInformation.from_dict(obj.get("eventsRepInfo")) if obj.get("eventsRepInfo") is not None else None,
            "notifUri": obj.get("notifUri"),
            "notifId": obj.get("notifId"),
            "eventNotifs": [NefEventNotification.from_dict(_item) for _item in obj.get("eventNotifs")] if obj.get("eventNotifs") is not None else None,
            "suppFeat": obj.get("suppFeat")
        })
        return _obj


