# coding: utf-8

"""
    Nnef_EventExposure

    NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from nnef.models.nef_event_filter import NefEventFilter
from nnef.models.reporting_information import ReportingInformation
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NefEventSubs(BaseModel):
    """
    Represents an event to be subscribed and the related event filter information.
    """ # noqa: E501
    event: StrictStr = Field(description="Represents a Network Exposure Event.   Possible values are: - SVC_EXPERIENCE: Indicates that the subscribed/notified event is service experience   information for an application. - UE_MOBILITY: Indicates that the subscribed/notified event is UE mobility information. - UE_COMM: Indicates that the subscribed/notified event is UE communication information. - EXCEPTIONS: Indicates that the subscribed/notified event is exceptions information. - USER_DATA_CONGESTION: Indicates that the subscribed/notified event is user data congestion   analytics related information. - PERF_DATA: Indicates that the subscribed/notified event is performance data information. - DISPERSION: Indicates that the subscribed/notified event is dispersion information. - COLLECTIVE_BEHAVIOUR: Indicates that the subscribed/notified event is collective behaviour   information. - MS_QOE_METRICS: Indicates that the subscribed/notified event is Media Streaming QoE   metrics. - MS_CONSUMPTION: Indicates that the subscribed/notified event is Media Streaming   consumption reports. - MS_NET_ASSIST_INVOCATION: Indicates that the subscribed/notified event is Media Streaming   network assistance invocation. - MS_DYN_POLICY_INVOCATION: Indicates that the subscribed/notified event is Media Streaming   dynamic policy invocation. - MS_ACCESS_ACTIVITY: Indicates that the subscribed/notified event is Media Streaming access   activity. - GNSS_ASSISTANCE_DATA: Indicates that the subscribed/notified event is GNSS Assistance Data   Collection. - DATA_VOLUME_TRANSFER_TIME: Indicates that the event subscribed is data volume transfer    time information. - APP_ACTIVE_TIME: Indicates that the event subscribed is application activation time   information. - SIGNALLING_INFO: Indicates that the event subscribed/notified is signalling information. ")
    event_filter: Optional[NefEventFilter] = Field(default=None, alias="eventFilter")
    event_rep_info: Optional[ReportingInformation] = Field(default=None, alias="eventRepInfo")
    __properties: ClassVar[List[str]] = ["event", "eventFilter", "eventRepInfo"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NefEventSubs from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of event_filter
        if self.event_filter:
            _dict['eventFilter'] = self.event_filter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of event_rep_info
        if self.event_rep_info:
            _dict['eventRepInfo'] = self.event_rep_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NefEventSubs from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event": obj.get("event"),
            "eventFilter": NefEventFilter.from_dict(obj.get("eventFilter")) if obj.get("eventFilter") is not None else None,
            "eventRepInfo": ReportingInformation.from_dict(obj.get("eventRepInfo")) if obj.get("eventRepInfo") is not None else None
        })
        return _obj


