# coding: utf-8

"""
    Nnef_EventExposure

    NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nnef.models.application_flow_description import ApplicationFlowDescription
from nnef.models.event_record_type import EventRecordType
from nnef.models.location_area5_g import LocationArea5G
from nnef.models.network_assistance_invocation_recommended_qo_s import NetworkAssistanceInvocationRecommendedQoS
from nnef.models.network_assistance_type import NetworkAssistanceType
from nnef.models.snssai import Snssai
from nnef.models.unidirectional_qo_s_specification import UnidirectionalQoSSpecification
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NetworkAssistanceInvocationEvent(BaseModel):
    """
    A Network Assistance Invocation Event record.
    """ # noqa: E501
    record_type: EventRecordType = Field(alias="recordType")
    record_timestamp: datetime = Field(description="string with format 'date-time' as defined in OpenAPI.", alias="recordTimestamp")
    app_id: StrictStr = Field(description="String providing an application identifier.", alias="appId")
    provisioning_session_id: Optional[StrictStr] = Field(default=None, description="String chosen by the 5GMS AF to serve as an identifier in a resource URI.", alias="provisioningSessionId")
    session_id: Optional[StrictStr] = Field(default=None, description="A unique identifier for a media delivery session.", alias="sessionId")
    ue_identification: Optional[StrictStr] = Field(default=None, description="GPSI of the requesting UE or a stable globally unique string identifying the requesting Media Session Handler. Present only for individual data sample record type and only when exposure is permitted by the data exposure restrictions in force for the event type in question.", alias="ueIdentification")
    data_network_name: Optional[StrictStr] = Field(default=None, description="String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \"Label1.Label2.Label3\"). ", alias="dataNetworkName")
    slice_id: Optional[Snssai] = Field(default=None, alias="sliceId")
    ue_locations: Optional[Annotated[List[LocationArea5G], Field(min_length=0)]] = Field(default=None, description="The location of the UE when the data described by this record was sampled. Present only for individual data sample record type and only when exposure is permitted by the data exposure restrictions in force for the event in question.", alias="ueLocations")
    policy_template_id: Optional[StrictStr] = Field(default=None, description="String chosen by the 5GMS AF to serve as an identifier in a resource URI.", alias="policyTemplateId")
    application_flow_descriptions: Optional[Annotated[List[Optional[ApplicationFlowDescription]], Field(min_length=1)]] = Field(default=None, alias="applicationFlowDescriptions")
    requested_qo_s: Optional[UnidirectionalQoSSpecification] = Field(default=None, alias="requestedQoS")
    recommended_qo_s: Optional[NetworkAssistanceInvocationRecommendedQoS] = Field(default=None, alias="recommendedQoS")
    network_assistance_type: NetworkAssistanceType = Field(alias="networkAssistanceType")
    __properties: ClassVar[List[str]] = ["recordType", "recordTimestamp", "appId", "provisioningSessionId", "sessionId", "ueIdentification", "dataNetworkName", "sliceId", "ueLocations", "policyTemplateId", "applicationFlowDescriptions", "requestedQoS", "recommendedQoS", "networkAssistanceType"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NetworkAssistanceInvocationEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of record_type
        if self.record_type:
            _dict['recordType'] = self.record_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of slice_id
        if self.slice_id:
            _dict['sliceId'] = self.slice_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in ue_locations (list)
        _items = []
        if self.ue_locations:
            for _item in self.ue_locations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ueLocations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in application_flow_descriptions (list)
        _items = []
        if self.application_flow_descriptions:
            for _item in self.application_flow_descriptions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['applicationFlowDescriptions'] = _items
        # override the default output from pydantic by calling `to_dict()` of requested_qo_s
        if self.requested_qo_s:
            _dict['requestedQoS'] = self.requested_qo_s.to_dict()
        # override the default output from pydantic by calling `to_dict()` of recommended_qo_s
        if self.recommended_qo_s:
            _dict['recommendedQoS'] = self.recommended_qo_s.to_dict()
        # override the default output from pydantic by calling `to_dict()` of network_assistance_type
        if self.network_assistance_type:
            _dict['networkAssistanceType'] = self.network_assistance_type.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NetworkAssistanceInvocationEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "recordType": EventRecordType.from_dict(obj.get("recordType")) if obj.get("recordType") is not None else None,
            "recordTimestamp": obj.get("recordTimestamp"),
            "appId": obj.get("appId"),
            "provisioningSessionId": obj.get("provisioningSessionId"),
            "sessionId": obj.get("sessionId"),
            "ueIdentification": obj.get("ueIdentification"),
            "dataNetworkName": obj.get("dataNetworkName"),
            "sliceId": Snssai.from_dict(obj.get("sliceId")) if obj.get("sliceId") is not None else None,
            "ueLocations": [LocationArea5G.from_dict(_item) for _item in obj.get("ueLocations")] if obj.get("ueLocations") is not None else None,
            "policyTemplateId": obj.get("policyTemplateId"),
            "applicationFlowDescriptions": [ApplicationFlowDescription.from_dict(_item) for _item in obj.get("applicationFlowDescriptions")] if obj.get("applicationFlowDescriptions") is not None else None,
            "requestedQoS": UnidirectionalQoSSpecification.from_dict(obj.get("requestedQoS")) if obj.get("requestedQoS") is not None else None,
            "recommendedQoS": NetworkAssistanceInvocationRecommendedQoS.from_dict(obj.get("recommendedQoS")) if obj.get("recommendedQoS") is not None else None,
            "networkAssistanceType": NetworkAssistanceType.from_dict(obj.get("networkAssistanceType")) if obj.get("networkAssistanceType") is not None else None
        })
        return _obj


