# coding: utf-8

"""
    Nnef_EventExposure

    NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nnef.models.pdu_set_handling_info import PduSetHandlingInfo
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PduSetQosPara(BaseModel):
    """
    Represents the PDU Set level QoS parameters.
    """ # noqa: E501
    pdu_set_delay_budget: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and 5.7.4 of 3GPP TS 23.501 [8])), expressed in 0.01 milliseconds. ", alias="pduSetDelayBudget")
    pdu_set_err_rate: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing Packet Error Rate (see clause 5.7.3.5 and 5.7.4 of 3GPP TS 23.501, expressed as a \"scalar x 10-k\" where the scalar and the exponent k are each encoded as one decimal digit. ", alias="pduSetErrRate")
    pdu_set_handling_info: Optional[PduSetHandlingInfo] = Field(default=None, alias="pduSetHandlingInfo")
    __properties: ClassVar[List[str]] = ["pduSetDelayBudget", "pduSetErrRate", "pduSetHandlingInfo"]

    @field_validator('pdu_set_err_rate')
    def pdu_set_err_rate_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([0-9]E-[0-9])$", value):
            raise ValueError(r"must validate the regular expression /^([0-9]E-[0-9])$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PduSetQosPara from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pdu_set_handling_info
        if self.pdu_set_handling_info:
            _dict['pduSetHandlingInfo'] = self.pdu_set_handling_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PduSetQosPara from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pduSetDelayBudget": obj.get("pduSetDelayBudget"),
            "pduSetErrRate": obj.get("pduSetErrRate"),
            "pduSetHandlingInfo": PduSetHandlingInfo.from_dict(obj.get("pduSetHandlingInfo")) if obj.get("pduSetHandlingInfo") is not None else None
        })
        return _obj


