# coding: utf-8

"""
    Nnef_EventExposure

    NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nnef.models.media_transport_proto import MediaTransportProto
from nnef.models.mri_transfer_method import MriTransferMethod
from nnef.models.rtp_header_ext_info import RtpHeaderExtInfo
from nnef.models.rtp_payload_info import RtpPayloadInfo
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ProtocolDescription(BaseModel):
    """
    ProtocolDescription contains information to derive PDU set information.
    """ # noqa: E501
    transport_proto: Optional[MediaTransportProto] = Field(default=None, alias="transportProto")
    rtp_header_ext_info: Optional[RtpHeaderExtInfo] = Field(default=None, alias="rtpHeaderExtInfo")
    add_rtp_header_ext_info: Optional[Annotated[List[RtpHeaderExtInfo], Field(min_length=1)]] = Field(default=None, alias="addRtpHeaderExtInfo")
    rtp_payload_info_list: Optional[Annotated[List[RtpPayloadInfo], Field(min_length=1)]] = Field(default=None, alias="rtpPayloadInfoList")
    mri_transfer_info: Optional[MriTransferMethod] = Field(default=None, alias="mriTransferInfo")
    __properties: ClassVar[List[str]] = ["transportProto", "rtpHeaderExtInfo", "addRtpHeaderExtInfo", "rtpPayloadInfoList", "mriTransferInfo"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProtocolDescription from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of transport_proto
        if self.transport_proto:
            _dict['transportProto'] = self.transport_proto.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rtp_header_ext_info
        if self.rtp_header_ext_info:
            _dict['rtpHeaderExtInfo'] = self.rtp_header_ext_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in add_rtp_header_ext_info (list)
        _items = []
        if self.add_rtp_header_ext_info:
            for _item in self.add_rtp_header_ext_info:
                if _item:
                    _items.append(_item.to_dict())
            _dict['addRtpHeaderExtInfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in rtp_payload_info_list (list)
        _items = []
        if self.rtp_payload_info_list:
            for _item in self.rtp_payload_info_list:
                if _item:
                    _items.append(_item.to_dict())
            _dict['rtpPayloadInfoList'] = _items
        # override the default output from pydantic by calling `to_dict()` of mri_transfer_info
        if self.mri_transfer_info:
            _dict['mriTransferInfo'] = self.mri_transfer_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ProtocolDescription from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "transportProto": MediaTransportProto.from_dict(obj.get("transportProto")) if obj.get("transportProto") is not None else None,
            "rtpHeaderExtInfo": RtpHeaderExtInfo.from_dict(obj.get("rtpHeaderExtInfo")) if obj.get("rtpHeaderExtInfo") is not None else None,
            "addRtpHeaderExtInfo": [RtpHeaderExtInfo.from_dict(_item) for _item in obj.get("addRtpHeaderExtInfo")] if obj.get("addRtpHeaderExtInfo") is not None else None,
            "rtpPayloadInfoList": [RtpPayloadInfo.from_dict(_item) for _item in obj.get("rtpPayloadInfoList")] if obj.get("rtpPayloadInfoList") is not None else None,
            "mriTransferInfo": MriTransferMethod.from_dict(obj.get("mriTransferInfo")) if obj.get("mriTransferInfo") is not None else None
        })
        return _obj


