# coding: utf-8

"""
    Nnef_EventExposure

    NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from nnef.models.block_type import BlockType
from nnef.models.connectivity_type import ConnectivityType
from nnef.models.rat_type import RatType
from nnef.models.ref_signal_type import RefSignalType
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RefSignalMeasurements(BaseModel):
    """
    Contains reference signal related information.
    """ # noqa: E501
    rat_type: Optional[RatType] = Field(default=None, alias="_ratType")
    ref_signal_type: Optional[RefSignalType] = Field(default=None, alias="_refSignalType")
    block_type: Optional[BlockType] = Field(default=None, alias="_blockType")
    rsrp: Optional[StrictStr] = Field(default=None, alias="_rsrp")
    rsrq: Optional[StrictStr] = Field(default=None, alias="_rsrq")
    sinr: Optional[StrictStr] = Field(default=None, alias="_sinr")
    bler: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="string with format 'float' as defined in OpenAPI.", alias="_bler")
    connectivity: Optional[ConnectivityType] = Field(default=None, alias="_connectivity")
    __properties: ClassVar[List[str]] = ["_ratType", "_refSignalType", "_blockType", "_rsrp", "_rsrq", "_sinr", "_bler", "_connectivity"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RefSignalMeasurements from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of rat_type
        if self.rat_type:
            _dict['_ratType'] = self.rat_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ref_signal_type
        if self.ref_signal_type:
            _dict['_refSignalType'] = self.ref_signal_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of block_type
        if self.block_type:
            _dict['_blockType'] = self.block_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of connectivity
        if self.connectivity:
            _dict['_connectivity'] = self.connectivity.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RefSignalMeasurements from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_ratType": RatType.from_dict(obj.get("_ratType")) if obj.get("_ratType") is not None else None,
            "_refSignalType": RefSignalType.from_dict(obj.get("_refSignalType")) if obj.get("_refSignalType") is not None else None,
            "_blockType": BlockType.from_dict(obj.get("_blockType")) if obj.get("_blockType") is not None else None,
            "_rsrp": obj.get("_rsrp"),
            "_rsrq": obj.get("_rsrq"),
            "_sinr": obj.get("_sinr"),
            "_bler": obj.get("_bler"),
            "_connectivity": ConnectivityType.from_dict(obj.get("_connectivity")) if obj.get("_connectivity") is not None else None
        })
        return _obj


