# coding: utf-8

"""
    Nnef_EventExposure

    NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nnef.models.ip_addr import IpAddr
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TargetUeIdentification(BaseModel):
    """
    Identifies the UE to which the request applies.
    """ # noqa: E501
    supis: Optional[Annotated[List[Annotated[str, Field(strict=True)]], Field(min_length=1)]] = None
    inter_group_ids: Optional[Annotated[List[Annotated[str, Field(strict=True)]], Field(min_length=1)]] = Field(default=None, alias="interGroupIds")
    any_ue_id: Optional[StrictBool] = Field(default=None, alias="anyUeId")
    ue_ip_addr: Optional[IpAddr] = Field(default=None, alias="ueIpAddr")
    __properties: ClassVar[List[str]] = ["supis", "interGroupIds", "anyUeId", "ueIpAddr"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TargetUeIdentification from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ue_ip_addr
        if self.ue_ip_addr:
            _dict['ueIpAddr'] = self.ue_ip_addr.to_dict()
        # set to None if ue_ip_addr (nullable) is None
        # and model_fields_set contains the field
        if self.ue_ip_addr is None and "ue_ip_addr" in self.model_fields_set:
            _dict['ueIpAddr'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TargetUeIdentification from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "supis": obj.get("supis"),
            "interGroupIds": obj.get("interGroupIds"),
            "anyUeId": obj.get("anyUeId"),
            "ueIpAddr": IpAddr.from_dict(obj.get("ueIpAddr")) if obj.get("ueIpAddr") is not None else None
        })
        return _obj


