# coding: utf-8

"""
    Nnef_EventExposure Notification (Callback Receiver)

    Callback receiver specification for the Nnef_EventExposure service.  This spec is consumed by NCOF (the NF service consumer) that subscribes to AF/RICF (acting as NEF in this PoC) events. The consumer must implement an HTTP server that exposes the endpoint defined here so that AF/RICF (acting as NEF in this PoC) can deliver notifications to it.  It is intentionally extracted from `TS29591_Nnef_EventExposure_PoC_ETRI_DoDo1.yaml` because OpenAPI Generator does not generate server stubs for the `callbacks:` section of an OpenAPI document. Generating from this standalone spec yields a ready-to-implement FastAPI server stub on the consumer side.  Schema simplifications applied for code-generator compatibility (the original `TS29591_Nnef_EventExposure_PoC_ETRI_DoDo1.yaml` is unchanged):   - `oneOf` constraints are dropped (validation deferred to business logic).   - 3GPP forward-compatible enum pattern (`anyOf: [enum-string, free-string]`)     is flattened to plain `type: string`.   - All cross-file `$ref`s are inlined into this single document.  6G-I2P ETRI-MoDuTec PoC Scenario. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CivicAddress(BaseModel):
    """
    Indicates a Civic address.
    """ # noqa: E501
    country: Optional[StrictStr] = None
    a1: Optional[StrictStr] = Field(default=None, alias="A1")
    a2: Optional[StrictStr] = Field(default=None, alias="A2")
    a3: Optional[StrictStr] = Field(default=None, alias="A3")
    a4: Optional[StrictStr] = Field(default=None, alias="A4")
    a5: Optional[StrictStr] = Field(default=None, alias="A5")
    a6: Optional[StrictStr] = Field(default=None, alias="A6")
    prd: Optional[StrictStr] = Field(default=None, alias="PRD")
    pod: Optional[StrictStr] = Field(default=None, alias="POD")
    sts: Optional[StrictStr] = Field(default=None, alias="STS")
    hno: Optional[StrictStr] = Field(default=None, alias="HNO")
    hns: Optional[StrictStr] = Field(default=None, alias="HNS")
    lmk: Optional[StrictStr] = Field(default=None, alias="LMK")
    loc: Optional[StrictStr] = Field(default=None, alias="LOC")
    nam: Optional[StrictStr] = Field(default=None, alias="NAM")
    pc: Optional[StrictStr] = Field(default=None, alias="PC")
    bld: Optional[StrictStr] = Field(default=None, alias="BLD")
    unit: Optional[StrictStr] = Field(default=None, alias="UNIT")
    flr: Optional[StrictStr] = Field(default=None, alias="FLR")
    room: Optional[StrictStr] = Field(default=None, alias="ROOM")
    plc: Optional[StrictStr] = Field(default=None, alias="PLC")
    pcn: Optional[StrictStr] = Field(default=None, alias="PCN")
    pobox: Optional[StrictStr] = Field(default=None, alias="POBOX")
    addcode: Optional[StrictStr] = Field(default=None, alias="ADDCODE")
    seat: Optional[StrictStr] = Field(default=None, alias="SEAT")
    rd: Optional[StrictStr] = Field(default=None, alias="RD")
    rdsec: Optional[StrictStr] = Field(default=None, alias="RDSEC")
    rdbr: Optional[StrictStr] = Field(default=None, alias="RDBR")
    rdsubbr: Optional[StrictStr] = Field(default=None, alias="RDSUBBR")
    prm: Optional[StrictStr] = Field(default=None, alias="PRM")
    pom: Optional[StrictStr] = Field(default=None, alias="POM")
    usage_rules: Optional[StrictStr] = Field(default=None, alias="usageRules")
    method: Optional[StrictStr] = None
    provided_by: Optional[StrictStr] = Field(default=None, alias="providedBy")
    __properties: ClassVar[List[str]] = ["country", "A1", "A2", "A3", "A4", "A5", "A6", "PRD", "POD", "STS", "HNO", "HNS", "LMK", "LOC", "NAM", "PC", "BLD", "UNIT", "FLR", "ROOM", "PLC", "PCN", "POBOX", "ADDCODE", "SEAT", "RD", "RDSEC", "RDBR", "RDSUBBR", "PRM", "POM", "usageRules", "method", "providedBy"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CivicAddress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CivicAddress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "country": obj.get("country"),
            "A1": obj.get("A1"),
            "A2": obj.get("A2"),
            "A3": obj.get("A3"),
            "A4": obj.get("A4"),
            "A5": obj.get("A5"),
            "A6": obj.get("A6"),
            "PRD": obj.get("PRD"),
            "POD": obj.get("POD"),
            "STS": obj.get("STS"),
            "HNO": obj.get("HNO"),
            "HNS": obj.get("HNS"),
            "LMK": obj.get("LMK"),
            "LOC": obj.get("LOC"),
            "NAM": obj.get("NAM"),
            "PC": obj.get("PC"),
            "BLD": obj.get("BLD"),
            "UNIT": obj.get("UNIT"),
            "FLR": obj.get("FLR"),
            "ROOM": obj.get("ROOM"),
            "PLC": obj.get("PLC"),
            "PCN": obj.get("PCN"),
            "POBOX": obj.get("POBOX"),
            "ADDCODE": obj.get("ADDCODE"),
            "SEAT": obj.get("SEAT"),
            "RD": obj.get("RD"),
            "RDSEC": obj.get("RDSEC"),
            "RDBR": obj.get("RDBR"),
            "RDSUBBR": obj.get("RDSUBBR"),
            "PRM": obj.get("PRM"),
            "POM": obj.get("POM"),
            "usageRules": obj.get("usageRules"),
            "method": obj.get("method"),
            "providedBy": obj.get("providedBy")
        })
        return _obj


