# coding: utf-8

"""
    Nnef_EventExposure Notification (Callback Receiver)

    Callback receiver specification for the Nnef_EventExposure service.  This spec is consumed by NCOF (the NF service consumer) that subscribes to AF/RICF (acting as NEF in this PoC) events. The consumer must implement an HTTP server that exposes the endpoint defined here so that AF/RICF (acting as NEF in this PoC) can deliver notifications to it.  It is intentionally extracted from `TS29591_Nnef_EventExposure_PoC_ETRI_DoDo1.yaml` because OpenAPI Generator does not generate server stubs for the `callbacks:` section of an OpenAPI document. Generating from this standalone spec yields a ready-to-implement FastAPI server stub on the consumer side.  Schema simplifications applied for code-generator compatibility (the original `TS29591_Nnef_EventExposure_PoC_ETRI_DoDo1.yaml` is unchanged):   - `oneOf` constraints are dropped (validation deferred to business logic).   - 3GPP forward-compatible enum pattern (`anyOf: [enum-string, free-string]`)     is flattened to plain `type: string`.   - All cross-file `$ref`s are inlined into this single document.  6G-I2P ETRI-MoDuTec PoC Scenario. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RedirectResponse(BaseModel):
    """
    The response shall include a Location header field containing a different URI  (pointing to a different URI of an other service instance), or the same URI if a request  is redirected to the same target resource via a different SCP. 
    """ # noqa: E501
    cause: Optional[StrictStr] = None
    target_scp: Optional[StrictStr] = Field(default=None, description="string providing an URI formatted according to IETF RFC 3986.", alias="targetScp")
    target_sepp: Optional[StrictStr] = Field(default=None, description="string providing an URI formatted according to IETF RFC 3986.", alias="targetSepp")
    __properties: ClassVar[List[str]] = ["cause", "targetScp", "targetSepp"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RedirectResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RedirectResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cause": obj.get("cause"),
            "targetScp": obj.get("targetScp"),
            "targetSepp": obj.get("targetSepp")
        })
        return _obj


