# coding: utf-8

"""
    Nnef_EventExposure

    NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nnef.models.application_flow_description import ApplicationFlowDescription
from nnef.models.network_assistance_invocation_recommended_qo_s import NetworkAssistanceInvocationRecommendedQoS
from nnef.models.unidirectional_qo_s_specification import UnidirectionalQoSSpecification
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NetworkAssistanceInvocation(BaseModel):
    """
    Common properties of a single Network Assistance invocation.
    """ # noqa: E501
    policy_template_id: Optional[StrictStr] = Field(default=None, description="String chosen by the 5GMS AF to serve as an identifier in a resource URI.", alias="policyTemplateId")
    application_flow_descriptions: Optional[Annotated[List[ApplicationFlowDescription], Field(min_length=1)]] = Field(default=None, alias="applicationFlowDescriptions")
    requested_qo_s: Optional[UnidirectionalQoSSpecification] = Field(default=None, alias="requestedQoS")
    recommended_qo_s: Optional[NetworkAssistanceInvocationRecommendedQoS] = Field(default=None, alias="recommendedQoS")
    __properties: ClassVar[List[str]] = ["policyTemplateId", "applicationFlowDescriptions", "requestedQoS", "recommendedQoS"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NetworkAssistanceInvocation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in application_flow_descriptions (list)
        _items = []
        if self.application_flow_descriptions:
            for _item in self.application_flow_descriptions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['applicationFlowDescriptions'] = _items
        # override the default output from pydantic by calling `to_dict()` of requested_qo_s
        if self.requested_qo_s:
            _dict['requestedQoS'] = self.requested_qo_s.to_dict()
        # override the default output from pydantic by calling `to_dict()` of recommended_qo_s
        if self.recommended_qo_s:
            _dict['recommendedQoS'] = self.recommended_qo_s.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NetworkAssistanceInvocation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "policyTemplateId": obj.get("policyTemplateId"),
            "applicationFlowDescriptions": [ApplicationFlowDescription.from_dict(_item) for _item in obj.get("applicationFlowDescriptions")] if obj.get("applicationFlowDescriptions") is not None else None,
            "requestedQoS": UnidirectionalQoSSpecification.from_dict(obj.get("requestedQoS")) if obj.get("requestedQoS") is not None else None,
            "recommendedQoS": NetworkAssistanceInvocationRecommendedQoS.from_dict(obj.get("recommendedQoS")) if obj.get("recommendedQoS") is not None else None
        })
        return _obj


