# coding: utf-8

"""
    Nnef_EventExposure

    NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RtpHeaderExtInfo(BaseModel):
    """
    RTP Header Extension information
    """ # noqa: E501
    rtp_header_ext_type: Optional[StrictStr] = Field(default=None, description="The enumeration indicates the type of Rtp Header Extension type  ", alias="rtpHeaderExtType")
    rtp_header_ext_id: Optional[Annotated[int, Field(le=255, strict=True, ge=1)]] = Field(default=None, alias="rtpHeaderExtId")
    long_format: Optional[StrictBool] = Field(default=None, alias="longFormat")
    pdu_set_size_active: Optional[StrictBool] = Field(default=None, alias="pduSetSizeActive")
    pdu_set_pdu_count_active: Optional[StrictBool] = Field(default=None, alias="pduSetPduCountActive")
    __properties: ClassVar[List[str]] = ["rtpHeaderExtType", "rtpHeaderExtId", "longFormat", "pduSetSizeActive", "pduSetPduCountActive"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RtpHeaderExtInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RtpHeaderExtInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rtpHeaderExtType": obj.get("rtpHeaderExtType"),
            "rtpHeaderExtId": obj.get("rtpHeaderExtId"),
            "longFormat": obj.get("longFormat"),
            "pduSetSizeActive": obj.get("pduSetSizeActive"),
            "pduSetPduCountActive": obj.get("pduSetPduCountActive")
        })
        return _obj


