# coding: utf-8

"""
    Nnef_EventExposure

    NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nnef.models.flow_info import FlowInfo
from nnef.models.time_window import TimeWindow
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UserDataCongestionCollection(BaseModel):
    """
    Contains User Data Congestion Analytics related information collection.
    """ # noqa: E501
    app_id: Optional[StrictStr] = Field(default=None, description="String providing an application identifier.", alias="appId")
    ip_traffic_filter: Optional[FlowInfo] = Field(default=None, alias="ipTrafficFilter")
    time_interv: Optional[TimeWindow] = Field(default=None, alias="timeInterv")
    thrput_ul: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ", alias="thrputUl")
    thrput_dl: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ", alias="thrputDl")
    thrput_pk_ul: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ", alias="thrputPkUl")
    thrput_pk_dl: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ", alias="thrputPkDl")
    __properties: ClassVar[List[str]] = ["appId", "ipTrafficFilter", "timeInterv", "thrputUl", "thrputDl", "thrputPkUl", "thrputPkDl"]

    @field_validator('thrput_ul')
    def thrput_ul_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$/")
        return value

    @field_validator('thrput_dl')
    def thrput_dl_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$/")
        return value

    @field_validator('thrput_pk_ul')
    def thrput_pk_ul_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$/")
        return value

    @field_validator('thrput_pk_dl')
    def thrput_pk_dl_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserDataCongestionCollection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ip_traffic_filter
        if self.ip_traffic_filter:
            _dict['ipTrafficFilter'] = self.ip_traffic_filter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of time_interv
        if self.time_interv:
            _dict['timeInterv'] = self.time_interv.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UserDataCongestionCollection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "appId": obj.get("appId"),
            "ipTrafficFilter": FlowInfo.from_dict(obj.get("ipTrafficFilter")) if obj.get("ipTrafficFilter") is not None else None,
            "timeInterv": TimeWindow.from_dict(obj.get("timeInterv")) if obj.get("timeInterv") is not None else None,
            "thrputUl": obj.get("thrputUl"),
            "thrputDl": obj.get("thrputDl"),
            "thrputPkUl": obj.get("thrputPkUl"),
            "thrputPkDl": obj.get("thrputPkDl")
        })
        return _obj


