# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nncof.models.time_window import TimeWindow
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AccuracyReq(BaseModel):
    """
    Represents the analytics accuracy requirement information.
    """ # noqa: E501
    accu_time_win: Optional[TimeWindow] = Field(default=None, alias="accuTimeWin")
    accu_period: Optional[StrictInt] = Field(default=None, description="indicating a time in seconds.", alias="accuPeriod")
    accu_dev_thr: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.", alias="accuDevThr")
    min_num: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.", alias="minNum")
    updated_ana_flg: Optional[StrictBool] = Field(default=None, description="Indicates the updated Analytics flag. Set to \"true\" indicates that the NCOF can provide the updated analytics if the analytics can be generated within the analytics accuracy information time window, which is specified by \"accuTimeWin\" attribute. Otherwise set to “false”. Default value is “false” if omitted. ", alias="updatedAnaFlg")
    correction_interval: Optional[StrictInt] = Field(default=None, description="indicating a time in seconds.", alias="correctionInterval")
    __properties: ClassVar[List[str]] = ["accuTimeWin", "accuPeriod", "accuDevThr", "minNum", "updatedAnaFlg", "correctionInterval"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccuracyReq from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of accu_time_win
        if self.accu_time_win:
            _dict['accuTimeWin'] = self.accu_time_win.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AccuracyReq from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accuTimeWin": TimeWindow.from_dict(obj.get("accuTimeWin")) if obj.get("accuTimeWin") is not None else None,
            "accuPeriod": obj.get("accuPeriod"),
            "accuDevThr": obj.get("accuDevThr"),
            "minNum": obj.get("minNum"),
            "updatedAnaFlg": obj.get("updatedAnaFlg"),
            "correctionInterval": obj.get("correctionInterval")
        })
        return _obj


