# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AccuracyInfo(BaseModel):
    """
    The analytics accuracy information.
    """ # noqa: E501
    accuracy_val: Annotated[int, Field(strict=True, ge=0)] = Field(description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.", alias="accuracyVal")
    accu_sample_nbr: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.", alias="accuSampleNbr")
    ana_accu_ind: Optional[StrictStr] = Field(default=None, description="Represents the notification methods for the subscribed events.   Possible values are: - MEET: Indicates meet the analytics accuracy requirement. - NOT_MEET: Indicates not meet the analytics accuracy requirement. ", alias="anaAccuInd")
    __properties: ClassVar[List[str]] = ["accuracyVal", "accuSampleNbr", "anaAccuInd"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccuracyInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AccuracyInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accuracyVal": obj.get("accuracyVal"),
            "accuSampleNbr": obj.get("accuSampleNbr"),
            "anaAccuInd": obj.get("anaAccuInd")
        })
        return _obj


