# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nncof.models.ncof_event import NcofEvent
from nncof.models.subscription_transfer_info import SubscriptionTransferInfo
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AnalyticsSubscriptionsTransfer(BaseModel):
    """
    Contains information about a request to transfer analytics subscriptions.
    """ # noqa: E501
    subs_trans_infos: Annotated[List[SubscriptionTransferInfo], Field(min_length=1)] = Field(alias="subsTransInfos")
    fail_trans_event_reports: Optional[Annotated[List[NcofEvent], Field(min_length=1)]] = Field(default=None, alias="failTransEventReports")
    __properties: ClassVar[List[str]] = ["subsTransInfos", "failTransEventReports"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AnalyticsSubscriptionsTransfer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in subs_trans_infos (list)
        _items = []
        if self.subs_trans_infos:
            for _item in self.subs_trans_infos:
                if _item:
                    _items.append(_item.to_dict())
            _dict['subsTransInfos'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in fail_trans_event_reports (list)
        _items = []
        if self.fail_trans_event_reports:
            for _item in self.fail_trans_event_reports:
                if _item:
                    _items.append(_item.to_dict())
            _dict['failTransEventReports'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AnalyticsSubscriptionsTransfer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subsTransInfos": [SubscriptionTransferInfo.from_dict(_item) for _item in obj.get("subsTransInfos")] if obj.get("subsTransInfos") is not None else None,
            "failTransEventReports": [NcofEvent.from_dict(_item) for _item in obj.get("failTransEventReports")] if obj.get("failTransEventReports") is not None else None
        })
        return _obj


