# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nncof.models.cell_power_para import CellPowerPara
from nncof.models.network_area_info import NetworkAreaInfo
from nncof.models.time_window import TimeWindow
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CellPowerParamSet(BaseModel):
    """
    The cell power parameter set.
    """ # noqa: E501
    cell_power_param_set: Optional[CellPowerPara] = Field(default=None, alias="_cellPowerParamSet")
    ctrl_time_win: Optional[TimeWindow] = Field(default=None, alias="_ctrlTimeWin")
    freqs: Optional[Annotated[List[Annotated[int, Field(le=3279165, strict=True, ge=0)]], Field(min_length=1)]] = Field(default=None, alias="_freqs")
    rat_types: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, alias="_ratTypes")
    validity_period: Optional[TimeWindow] = Field(default=None, alias="_validityPeriod")
    spatial_validity: Optional[NetworkAreaInfo] = Field(default=None, alias="_spatialValidity")
    __properties: ClassVar[List[str]] = ["_cellPowerParamSet", "_ctrlTimeWin", "_freqs", "_ratTypes", "_validityPeriod", "_spatialValidity"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CellPowerParamSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cell_power_param_set
        if self.cell_power_param_set:
            _dict['_cellPowerParamSet'] = self.cell_power_param_set.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ctrl_time_win
        if self.ctrl_time_win:
            _dict['_ctrlTimeWin'] = self.ctrl_time_win.to_dict()
        # override the default output from pydantic by calling `to_dict()` of validity_period
        if self.validity_period:
            _dict['_validityPeriod'] = self.validity_period.to_dict()
        # override the default output from pydantic by calling `to_dict()` of spatial_validity
        if self.spatial_validity:
            _dict['_spatialValidity'] = self.spatial_validity.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CellPowerParamSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_cellPowerParamSet": CellPowerPara.from_dict(obj.get("_cellPowerParamSet")) if obj.get("_cellPowerParamSet") is not None else None,
            "_ctrlTimeWin": TimeWindow.from_dict(obj.get("_ctrlTimeWin")) if obj.get("_ctrlTimeWin") is not None else None,
            "_freqs": obj.get("_freqs"),
            "_ratTypes": obj.get("_ratTypes"),
            "_validityPeriod": TimeWindow.from_dict(obj.get("_validityPeriod")) if obj.get("_validityPeriod") is not None else None,
            "_spatialValidity": NetworkAreaInfo.from_dict(obj.get("_spatialValidity")) if obj.get("_spatialValidity") is not None else None
        })
        return _obj


