# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nncof.models.data_volume import DataVolume
from nncof.models.e2e_data_vol_trans_time_criterion import E2eDataVolTransTimeCriterion
from nncof.models.matching_direction import MatchingDirection
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class E2eDataVolTransTimeReq(BaseModel):
    """
    Represents other E2E data volume transfer time analytics requirements.
    """ # noqa: E501
    criterion: Optional[E2eDataVolTransTimeCriterion] = None
    order: Optional[MatchingDirection] = None
    high_trans_tm_thr: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.", alias="highTransTmThr")
    low_trans_tm_thr: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.", alias="lowTransTmThr")
    repeat_data_trans: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.", alias="repeatDataTrans")
    ts_interval_data_trans: Optional[StrictInt] = Field(default=None, description="indicating a time in seconds.", alias="tsIntervalDataTrans")
    data_volume: Optional[DataVolume] = Field(default=None, alias="dataVolume")
    max_number_ues: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.", alias="maxNumberUes")
    __properties: ClassVar[List[str]] = ["criterion", "order", "highTransTmThr", "lowTransTmThr", "repeatDataTrans", "tsIntervalDataTrans", "dataVolume", "maxNumberUes"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of E2eDataVolTransTimeReq from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of criterion
        if self.criterion:
            _dict['criterion'] = self.criterion.to_dict()
        # override the default output from pydantic by calling `to_dict()` of order
        if self.order:
            _dict['order'] = self.order.to_dict()
        # override the default output from pydantic by calling `to_dict()` of data_volume
        if self.data_volume:
            _dict['dataVolume'] = self.data_volume.to_dict()
        # set to None if data_volume (nullable) is None
        # and model_fields_set contains the field
        if self.data_volume is None and "data_volume" in self.model_fields_set:
            _dict['dataVolume'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of E2eDataVolTransTimeReq from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "criterion": E2eDataVolTransTimeCriterion.from_dict(obj.get("criterion")) if obj.get("criterion") is not None else None,
            "order": MatchingDirection.from_dict(obj.get("order")) if obj.get("order") is not None else None,
            "highTransTmThr": obj.get("highTransTmThr"),
            "lowTransTmThr": obj.get("lowTransTmThr"),
            "repeatDataTrans": obj.get("repeatDataTrans"),
            "tsIntervalDataTrans": obj.get("tsIntervalDataTrans"),
            "dataVolume": DataVolume.from_dict(obj.get("dataVolume")) if obj.get("dataVolume") is not None else None,
            "maxNumberUes": obj.get("maxNumberUes")
        })
        return _obj


