# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from nncof.models.gad_shape import GADShape
from nncof.models.geographical_coordinates import GeographicalCoordinates
from nncof.models.supported_gad_shapes import SupportedGADShapes
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EllipsoidArc(GADShape):
    """
    Ellipsoid Arc.
    """ # noqa: E501
    shape: SupportedGADShapes
    point: GeographicalCoordinates
    inner_radius: Annotated[int, Field(le=327675, strict=True, ge=0)] = Field(description="Indicates value of the inner radius.", alias="innerRadius")
    uncertainty_radius: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(description="Indicates value of uncertainty.", alias="uncertaintyRadius")
    offset_angle: Annotated[int, Field(le=360, strict=True, ge=0)] = Field(description="Indicates value of angle.", alias="offsetAngle")
    included_angle: Annotated[int, Field(le=360, strict=True, ge=0)] = Field(description="Indicates value of angle.", alias="includedAngle")
    confidence: Annotated[int, Field(le=100, strict=True, ge=0)] = Field(description="Indicates value of confidence.")
    __properties: ClassVar[List[str]] = ["shape", "point", "innerRadius", "uncertaintyRadius", "offsetAngle", "includedAngle", "confidence"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EllipsoidArc from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of shape
        if self.shape:
            _dict['shape'] = self.shape.to_dict()
        # override the default output from pydantic by calling `to_dict()` of point
        if self.point:
            _dict['point'] = self.point.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EllipsoidArc from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "shape": SupportedGADShapes.from_dict(obj.get("shape")) if obj.get("shape") is not None else None,
            "point": GeographicalCoordinates.from_dict(obj.get("point")) if obj.get("point") is not None else None,
            "innerRadius": obj.get("innerRadius"),
            "uncertaintyRadius": obj.get("uncertaintyRadius"),
            "offsetAngle": obj.get("offsetAngle"),
            "includedAngle": obj.get("includedAngle"),
            "confidence": obj.get("confidence")
        })
        return _obj


