# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nncof.models.accuracy_info import AccuracyInfo
from nncof.models.analytics_metadata_info import AnalyticsMetadataInfo
from nncof.models.cell_power_ctrl_info import CellPowerCtrlInfo
from nncof.models.e2e_data_vol_trans_time_info import E2eDataVolTransTimeInfo
from nncof.models.ncof_event import NcofEvent
from nncof.models.ncof_failure_code import NcofFailureCode
from nncof.models.qos_policy_assist_info import QosPolicyAssistInfo
from nncof.models.service_experience_info import ServiceExperienceInfo
from nncof.models.wlan_performance_info import WlanPerformanceInfo
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EventNotification(BaseModel):
    """
    Represents a notification on events that occurred.
    """ # noqa: E501
    event: NcofEvent
    start: Optional[datetime] = Field(default=None, description="string with format 'date-time' as defined in OpenAPI.")
    expiry: Optional[datetime] = Field(default=None, description="string with format 'date-time' as defined in OpenAPI.")
    time_stamp_gen: Optional[datetime] = Field(default=None, description="string with format 'date-time' as defined in OpenAPI.", alias="timeStampGen")
    fail_notify_code: Optional[NcofFailureCode] = Field(default=None, alias="failNotifyCode")
    rv_wait_time: Optional[StrictInt] = Field(default=None, description="indicating a time in seconds.", alias="rvWaitTime")
    ana_meta_info: Optional[AnalyticsMetadataInfo] = Field(default=None, alias="anaMetaInfo")
    svc_exps: Optional[Annotated[List[ServiceExperienceInfo], Field(min_length=1)]] = Field(default=None, alias="svcExps")
    wlan_infos: Optional[Annotated[List[WlanPerformanceInfo], Field(min_length=1)]] = Field(default=None, alias="wlanInfos")
    data_vl_trns_tm_infos: Optional[Annotated[List[E2eDataVolTransTimeInfo], Field(min_length=1)]] = Field(default=None, alias="dataVlTrnsTmInfos")
    accu_info: Optional[AccuracyInfo] = Field(default=None, alias="accuInfo")
    cancel_accu_ind: Optional[StrictBool] = Field(default=None, description="Indicates cancelled subscription of the analytics accuracy information. Set to \"true\" indicates the NCOF cancelled subscription of analytics accuracy information as the NCOF does not support the accuracy checking capability. Otherwise set to \"false\". Default value is \"false\" if omitted. ", alias="cancelAccuInd")
    pause_ind: Optional[StrictBool] = Field(default=None, description="Pause analytics consumption indication. Set to \"true\" to indicate the consumer to stop the consumption of the analytics. Default value is \"false\" if omitted. ", alias="pauseInd")
    resume_ind: Optional[StrictBool] = Field(default=None, description="Resume analytics consumption indication. Set to \"true\" to indicate the consumer to resume the consumption of the analytics. Default value is \"false\" if omitted. ", alias="resumeInd")
    ctrl_event_ind: Optional[StrictBool] = Field(default=None, description="Control event indication. Set to \"true\" to indicate the desired event is control event  rather than analytics one. ", alias="_ctrlEventInd")
    qos_pol_assist_infos: Optional[Annotated[List[QosPolicyAssistInfo], Field(min_length=1)]] = Field(default=None, description="The QoS and policy assistance information.", alias="qosPolAssistInfos")
    cell_power_ctrl_opt_infos: Optional[Annotated[List[CellPowerCtrlInfo], Field(min_length=1)]] = Field(default=None, description="The cell power control and optimization information.", alias="_cellPowerCtrlOptInfos")
    __properties: ClassVar[List[str]] = ["event", "start", "expiry", "timeStampGen", "failNotifyCode", "rvWaitTime", "anaMetaInfo", "svcExps", "wlanInfos", "dataVlTrnsTmInfos", "accuInfo", "cancelAccuInd", "pauseInd", "resumeInd", "_ctrlEventInd", "qosPolAssistInfos", "_cellPowerCtrlOptInfos"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EventNotification from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of event
        if self.event:
            _dict['event'] = self.event.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fail_notify_code
        if self.fail_notify_code:
            _dict['failNotifyCode'] = self.fail_notify_code.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ana_meta_info
        if self.ana_meta_info:
            _dict['anaMetaInfo'] = self.ana_meta_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in svc_exps (list)
        _items = []
        if self.svc_exps:
            for _item in self.svc_exps:
                if _item:
                    _items.append(_item.to_dict())
            _dict['svcExps'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in wlan_infos (list)
        _items = []
        if self.wlan_infos:
            for _item in self.wlan_infos:
                if _item:
                    _items.append(_item.to_dict())
            _dict['wlanInfos'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in data_vl_trns_tm_infos (list)
        _items = []
        if self.data_vl_trns_tm_infos:
            for _item in self.data_vl_trns_tm_infos:
                if _item:
                    _items.append(_item.to_dict())
            _dict['dataVlTrnsTmInfos'] = _items
        # override the default output from pydantic by calling `to_dict()` of accu_info
        if self.accu_info:
            _dict['accuInfo'] = self.accu_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in qos_pol_assist_infos (list)
        _items = []
        if self.qos_pol_assist_infos:
            for _item in self.qos_pol_assist_infos:
                if _item:
                    _items.append(_item.to_dict())
            _dict['qosPolAssistInfos'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cell_power_ctrl_opt_infos (list)
        _items = []
        if self.cell_power_ctrl_opt_infos:
            for _item in self.cell_power_ctrl_opt_infos:
                if _item:
                    _items.append(_item.to_dict())
            _dict['_cellPowerCtrlOptInfos'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EventNotification from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event": NcofEvent.from_dict(obj.get("event")) if obj.get("event") is not None else None,
            "start": obj.get("start"),
            "expiry": obj.get("expiry"),
            "timeStampGen": obj.get("timeStampGen"),
            "failNotifyCode": NcofFailureCode.from_dict(obj.get("failNotifyCode")) if obj.get("failNotifyCode") is not None else None,
            "rvWaitTime": obj.get("rvWaitTime"),
            "anaMetaInfo": AnalyticsMetadataInfo.from_dict(obj.get("anaMetaInfo")) if obj.get("anaMetaInfo") is not None else None,
            "svcExps": [ServiceExperienceInfo.from_dict(_item) for _item in obj.get("svcExps")] if obj.get("svcExps") is not None else None,
            "wlanInfos": [WlanPerformanceInfo.from_dict(_item) for _item in obj.get("wlanInfos")] if obj.get("wlanInfos") is not None else None,
            "dataVlTrnsTmInfos": [E2eDataVolTransTimeInfo.from_dict(_item) for _item in obj.get("dataVlTrnsTmInfos")] if obj.get("dataVlTrnsTmInfos") is not None else None,
            "accuInfo": AccuracyInfo.from_dict(obj.get("accuInfo")) if obj.get("accuInfo") is not None else None,
            "cancelAccuInd": obj.get("cancelAccuInd"),
            "pauseInd": obj.get("pauseInd"),
            "resumeInd": obj.get("resumeInd"),
            "_ctrlEventInd": obj.get("_ctrlEventInd"),
            "qosPolAssistInfos": [QosPolicyAssistInfo.from_dict(_item) for _item in obj.get("qosPolAssistInfos")] if obj.get("qosPolAssistInfos") is not None else None,
            "_cellPowerCtrlOptInfos": [CellPowerCtrlInfo.from_dict(_item) for _item in obj.get("_cellPowerCtrlOptInfos")] if obj.get("_cellPowerCtrlOptInfos") is not None else None
        })
        return _obj


