# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from nncof.models.exception_id import ExceptionId
from nncof.models.exception_trend import ExceptionTrend
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Exception(BaseModel):
    """
    Represents the Exception information.
    """ # noqa: E501
    excep_id: ExceptionId = Field(alias="excepId")
    excep_level: Optional[StrictInt] = Field(default=None, alias="excepLevel")
    excep_trend: Optional[ExceptionTrend] = Field(default=None, alias="excepTrend")
    __properties: ClassVar[List[str]] = ["excepId", "excepLevel", "excepTrend"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Exception from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of excep_id
        if self.excep_id:
            _dict['excepId'] = self.excep_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of excep_trend
        if self.excep_trend:
            _dict['excepTrend'] = self.excep_trend.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Exception from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "excepId": ExceptionId.from_dict(obj.get("excepId")) if obj.get("excepId") is not None else None,
            "excepLevel": obj.get("excepLevel"),
            "excepTrend": ExceptionTrend.from_dict(obj.get("excepTrend")) if obj.get("excepTrend") is not None else None
        })
        return _obj


