# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBytes, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nncof.models.hfc_node_id import HfcNodeId
from nncof.models.ipv6_addr import Ipv6Addr
from nncof.models.tai import Tai
from nncof.models.tnap_id import TnapId
from nncof.models.twap_id import TwapId
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class N3gaLocation(BaseModel):
    """
    Contains the Non-3GPP access user location.
    """ # noqa: E501
    n3gpp_tai: Optional[Tai] = Field(default=None, alias="n3gppTai")
    n3_iwf_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="This IE shall contain the N3IWF identifier received over NGAP and shall be encoded as a  string of hexadecimal characters. Each character in the string shall take a value of \"0\"  to \"9\", \"a\" to \"f\" or \"A\" to \"F\" and shall represent 4 bits. The most significant  character representing the 4 most significant bits of the N3IWF ID shall appear first in  the string, and the character representing the 4 least significant bit of the N3IWF ID  shall appear last in the string.  ", alias="n3IwfId")
    ue_ipv4_addr: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166. ", alias="ueIpv4Addr")
    ue_ipv6_addr: Optional[Ipv6Addr] = Field(default=None, alias="ueIpv6Addr")
    port_number: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.", alias="portNumber")
    protocol: Optional[StrictStr] = Field(default=None, description="Possible values are: - UDP: User Datagram Protocol. - TCP: Transmission Control Protocol.  ")
    tnap_id: Optional[TnapId] = Field(default=None, alias="tnapId")
    twap_id: Optional[TwapId] = Field(default=None, alias="twapId")
    hfc_node_id: Optional[HfcNodeId] = Field(default=None, alias="hfcNodeId")
    gli: Optional[Union[StrictBytes, StrictStr]] = Field(default=None, description="string with format 'bytes' as defined in OpenAPI")
    w5gban_line_type: Optional[StrictStr] = Field(default=None, description="Possible values are: - DSL: Identifies a DSL line - PON: Identifies a PON line ", alias="w5gbanLineType")
    gci: Optional[StrictStr] = Field(default=None, description="Global Cable Identifier uniquely identifying the connection between the 5G-CRG or FN-CRG to the 5GS. See clause 28.15.4 of 3GPP TS 23.003. This shall be encoded as a string per clause 28.15.4 of 3GPP TS 23.003, and compliant with the syntax specified  in clause 2.2  of IETF RFC 7542 for the username part of a NAI. The GCI value is specified in CableLabs WR-TR-5WWC-ARCH. ")
    __properties: ClassVar[List[str]] = ["n3gppTai", "n3IwfId", "ueIpv4Addr", "ueIpv6Addr", "portNumber", "protocol", "tnapId", "twapId", "hfcNodeId", "gli", "w5gbanLineType", "gci"]

    @field_validator('n3_iwf_id')
    def n3_iwf_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Fa-f0-9]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]+$/")
        return value

    @field_validator('ue_ipv4_addr')
    def ue_ipv4_addr_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$", value):
            raise ValueError(r"must validate the regular expression /^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of N3gaLocation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of n3gpp_tai
        if self.n3gpp_tai:
            _dict['n3gppTai'] = self.n3gpp_tai.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ue_ipv6_addr
        if self.ue_ipv6_addr:
            _dict['ueIpv6Addr'] = self.ue_ipv6_addr.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tnap_id
        if self.tnap_id:
            _dict['tnapId'] = self.tnap_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of twap_id
        if self.twap_id:
            _dict['twapId'] = self.twap_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hfc_node_id
        if self.hfc_node_id:
            _dict['hfcNodeId'] = self.hfc_node_id.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of N3gaLocation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "n3gppTai": Tai.from_dict(obj.get("n3gppTai")) if obj.get("n3gppTai") is not None else None,
            "n3IwfId": obj.get("n3IwfId"),
            "ueIpv4Addr": obj.get("ueIpv4Addr"),
            "ueIpv6Addr": Ipv6Addr.from_dict(obj.get("ueIpv6Addr")) if obj.get("ueIpv6Addr") is not None else None,
            "portNumber": obj.get("portNumber"),
            "protocol": obj.get("protocol"),
            "tnapId": TnapId.from_dict(obj.get("tnapId")) if obj.get("tnapId") is not None else None,
            "twapId": TwapId.from_dict(obj.get("twapId")) if obj.get("twapId") is not None else None,
            "hfcNodeId": HfcNodeId.from_dict(obj.get("hfcNodeId")) if obj.get("hfcNodeId") is not None else None,
            "gli": obj.get("gli"),
            "w5gbanLineType": obj.get("w5gbanLineType"),
            "gci": obj.get("gci")
        })
        return _obj


