# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nncof.models.plmn_id_nid import PlmnIdNid
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NtnTaiInfo(BaseModel):
    """
    Contains NR NTN TAI Information.
    """ # noqa: E501
    plmn_id: PlmnIdNid = Field(alias="plmnId")
    tac_list: Annotated[List[Annotated[str, Field(strict=True)]], Field(min_length=1)] = Field(alias="tacList")
    derived_tac: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="2 or 3-octet string identifying a tracking area code as specified in clause 9.3.3.10  of 3GPP TS 38.413, in hexadecimal representation. Each character in the string shall  take a value of \"0\" to \"9\", \"a\" to \"f\" or \"A\" to \"F\" and shall represent 4 bits. The most significant character representing the 4 most significant bits of the TAC shall  appear first in the string, and the character representing the 4 least significant bit  of the TAC shall appear last in the string.  ", alias="derivedTac")
    __properties: ClassVar[List[str]] = ["plmnId", "tacList", "derivedTac"]

    @field_validator('derived_tac')
    def derived_tac_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"(^[A-Fa-f0-9]{4}$)|(^[A-Fa-f0-9]{6}$)", value):
            raise ValueError(r"must validate the regular expression /(^[A-Fa-f0-9]{4}$)|(^[A-Fa-f0-9]{6}$)/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NtnTaiInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of plmn_id
        if self.plmn_id:
            _dict['plmnId'] = self.plmn_id.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NtnTaiInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "plmnId": PlmnIdNid.from_dict(obj.get("plmnId")) if obj.get("plmnId") is not None else None,
            "tacList": obj.get("tacList"),
            "derivedTac": obj.get("derivedTac")
        })
        return _obj


