# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nncof.models.access_type import AccessType
from nncof.models.pdu_session_type import PduSessionType
from nncof.models.ssc_mode import SscMode
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PduSessionInfo(BaseModel):
    """
    Represents combination of PDU Session parameter(s) information.
    """ # noqa: E501
    pdu_sess_type: Optional[PduSessionType] = Field(default=None, alias="pduSessType")
    ssc_mode: Optional[SscMode] = Field(default=None, alias="sscMode")
    access_types: Optional[Annotated[List[AccessType], Field(min_length=1)]] = Field(default=None, alias="accessTypes")
    __properties: ClassVar[List[str]] = ["pduSessType", "sscMode", "accessTypes"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PduSessionInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pdu_sess_type
        if self.pdu_sess_type:
            _dict['pduSessType'] = self.pdu_sess_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ssc_mode
        if self.ssc_mode:
            _dict['sscMode'] = self.ssc_mode.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PduSessionInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pduSessType": PduSessionType.from_dict(obj.get("pduSessType")) if obj.get("pduSessType") is not None else None,
            "sscMode": SscMode.from_dict(obj.get("sscMode")) if obj.get("sscMode") is not None else None,
            "accessTypes": obj.get("accessTypes")
        })
        return _obj


