# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nncof.models.velocity_estimate import VelocityEstimate
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class QosRequirement(BaseModel):
    """
    Represents the QoS requirements.
    """ # noqa: E501
    var_5qi: Optional[Annotated[int, Field(le=255, strict=True, ge=0)]] = Field(default=None, description="Unsigned integer representing a 5G QoS Identifier (see clause 5.7.2.1 of 3GPP TS 23.501, within the range 0 to 255. ", alias="5qi")
    gfbr_ul: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ", alias="gfbrUl")
    gfbr_dl: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ", alias="gfbrDl")
    res_type: Optional[StrictStr] = Field(default=None, description="The enumeration QosResourceType indicates whether a QoS Flow is non-GBR, delay critical GBR, or non-delay critical GBR (see clauses 5.7.3.4 and 5.7.3.5 of 3GPP TS 23.501). It shall comply with the provisions defined in table 5.5.3.6-1.  ", alias="resType")
    pdb: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and 5.7.4 of 3GPP TS 23.501), expressed in milliseconds. ")
    per: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing Packet Error Rate (see clause 5.7.3.5 and 5.7.4 of 3GPP TS 23.501, expressed as a \"scalar x 10-k\" where the scalar and the exponent k are each encoded as one decimal digit. ")
    device_speed: Optional[VelocityEstimate] = Field(default=None, alias="deviceSpeed")
    device_type: Optional[StrictStr] = Field(default=None, description="Represents the device type.   Possible values are:     - MOBILE_PHONE: Mobile Phone.   - SMART_PHONE: Smartphone.   - TABLET: Tablet.   - DONGLE: Dongle.   - MODEM: Modem.   - WLAN_ROUTER: WLAN Router.   - IOT_DEVICE: IoT Device.   - WEARABLE: Wearable.   - MOBILE_TEST_PLATFORM: Mobile Test Platform.   - UNDEFINED: Undefined. ", alias="deviceType")
    __properties: ClassVar[List[str]] = ["5qi", "gfbrUl", "gfbrDl", "resType", "pdb", "per", "deviceSpeed", "deviceType"]

    @field_validator('gfbr_ul')
    def gfbr_ul_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$/")
        return value

    @field_validator('gfbr_dl')
    def gfbr_dl_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$/")
        return value

    @field_validator('per')
    def per_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([0-9]E-[0-9])$", value):
            raise ValueError(r"must validate the regular expression /^([0-9]E-[0-9])$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of QosRequirement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of device_speed
        if self.device_speed:
            _dict['deviceSpeed'] = self.device_speed.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of QosRequirement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "5qi": obj.get("5qi"),
            "gfbrUl": obj.get("gfbrUl"),
            "gfbrDl": obj.get("gfbrDl"),
            "resType": obj.get("resType"),
            "pdb": obj.get("pdb"),
            "per": obj.get("per"),
            "deviceSpeed": VelocityEstimate.from_dict(obj.get("deviceSpeed")) if obj.get("deviceSpeed") is not None else None,
            "deviceType": obj.get("deviceType")
        })
        return _obj


