# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nncof.models.qos_resource_type import QosResourceType
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class QosPara(BaseModel):
    """
    The values of the QoS parameters.
    """ # noqa: E501
    qos_param_set_id: Optional[StrictStr] = Field(default=None, description="Identifies the QoS parameter set.", alias="qosParamSetId")
    var_5qi: Optional[Annotated[int, Field(le=255, strict=True, ge=0)]] = Field(default=None, description="Unsigned integer representing a 5G QoS Identifier (see clause 5.7.2.1 of 3GPP TS 23.501, within the range 0 to 255. ", alias="5qi")
    priority_lvl: Optional[Annotated[int, Field(le=127, strict=True, ge=1)]] = Field(default=None, description="Unsigned integer indicating the 5QI Priority Level (see clauses 5.7.3.3 and 5.7.4 of 3GPP TS 23.501, within the range 1 to 127.Values are ordered in decreasing order of priority,  i.e. with 1 as the highest priority and 127 as the lowest priority.  ", alias="priorityLvl")
    rsc_type: Optional[QosResourceType] = Field(default=None, alias="rscType")
    pdb: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and 5.7.4 of 3GPP TS 23.501), expressed in milliseconds. ")
    per: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing Packet Error Rate (see clause 5.7.3.5 and 5.7.4 of 3GPP TS 23.501, expressed as a \"scalar x 10-k\" where the scalar and the exponent k are each encoded as one decimal digit. ")
    gbr_ul: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ", alias="gbrUl")
    gbr_dl: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ", alias="gbrDl")
    mbr_ul: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ", alias="mbrUl")
    mbr_dl: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ", alias="mbrDl")
    max_plr_ul: Optional[Annotated[int, Field(le=1000, strict=True, ge=0)]] = Field(default=None, description="Unsigned integer indicating Packet Loss Rate (see clauses 5.7.2.8 and 5.7.4 of 3GPP TS 23.501), expressed in tenth of percent. ", alias="maxPlrUl")
    max_plr_dl: Optional[Annotated[int, Field(le=1000, strict=True, ge=0)]] = Field(default=None, description="Unsigned integer indicating Packet Loss Rate (see clauses 5.7.2.8 and 5.7.4 of 3GPP TS 23.501), expressed in tenth of percent. ", alias="maxPlrDl")
    avg_win: Optional[Annotated[int, Field(le=4095, strict=True, ge=1)]] = Field(default=2000, description="Unsigned integer indicating Averaging Window (see clause 5.7.3.6 and 5.7.4 of 3GPP TS 23.501), expressed in milliseconds.  ", alias="avgWin")
    max_data_burst_vol: Optional[Annotated[int, Field(le=4095, strict=True, ge=1)]] = Field(default=None, description="Unsigned integer indicating Maximum Data Burst Volume (see clauses 5.7.3.7 and 5.7.4 of 3GPP TS 23.501), expressed in Bytes.  ", alias="maxDataBurstVol")
    __properties: ClassVar[List[str]] = ["qosParamSetId", "5qi", "priorityLvl", "rscType", "pdb", "per", "gbrUl", "gbrDl", "mbrUl", "mbrDl", "maxPlrUl", "maxPlrDl", "avgWin", "maxDataBurstVol"]

    @field_validator('per')
    def per_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^([0-9]E-[0-9])$", value):
            raise ValueError(r"must validate the regular expression /^([0-9]E-[0-9])$/")
        return value

    @field_validator('gbr_ul')
    def gbr_ul_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$/")
        return value

    @field_validator('gbr_dl')
    def gbr_dl_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$/")
        return value

    @field_validator('mbr_ul')
    def mbr_ul_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$/")
        return value

    @field_validator('mbr_dl')
    def mbr_dl_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of QosPara from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of rsc_type
        if self.rsc_type:
            _dict['rscType'] = self.rsc_type.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of QosPara from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "qosParamSetId": obj.get("qosParamSetId"),
            "5qi": obj.get("5qi"),
            "priorityLvl": obj.get("priorityLvl"),
            "rscType": QosResourceType.from_dict(obj.get("rscType")) if obj.get("rscType") is not None else None,
            "pdb": obj.get("pdb"),
            "per": obj.get("per"),
            "gbrUl": obj.get("gbrUl"),
            "gbrDl": obj.get("gbrDl"),
            "mbrUl": obj.get("mbrUl"),
            "mbrDl": obj.get("mbrDl"),
            "maxPlrUl": obj.get("maxPlrUl"),
            "maxPlrDl": obj.get("maxPlrDl"),
            "avgWin": obj.get("avgWin") if obj.get("avgWin") is not None else 2000,
            "maxDataBurstVol": obj.get("maxDataBurstVol")
        })
        return _obj


