# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nncof.models.matching_direction import MatchingDirection
from nncof.models.qos_para import QosPara
from nncof.models.qos_pol_order_criterion import QosPolOrderCriterion
from nncof.models.rat_type import RatType
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class QosPolicyAssistReq(BaseModel):
    """
    The QoS and policy assistance analytics requirement information.
    """ # noqa: E501
    order_criterion: Optional[QosPolOrderCriterion] = Field(default=None, alias="orderCriterion")
    order_direction: Optional[MatchingDirection] = Field(default=None, alias="orderDirection")
    freqs: Optional[Annotated[List[Annotated[int, Field(le=3279165, strict=True, ge=0)]], Field(min_length=1)]] = None
    rat_types: Optional[Annotated[List[RatType], Field(min_length=1)]] = Field(default=None, alias="ratTypes")
    qos_param_sets: Annotated[List[QosPara], Field(min_length=1)] = Field(alias="qosParamSets")
    requested_qoe: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="string with format 'float' as defined in OpenAPI.", alias="requestedQoe")
    __properties: ClassVar[List[str]] = ["orderCriterion", "orderDirection", "freqs", "ratTypes", "qosParamSets", "requestedQoe"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of QosPolicyAssistReq from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of order_criterion
        if self.order_criterion:
            _dict['orderCriterion'] = self.order_criterion.to_dict()
        # override the default output from pydantic by calling `to_dict()` of order_direction
        if self.order_direction:
            _dict['orderDirection'] = self.order_direction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in rat_types (list)
        _items = []
        if self.rat_types:
            for _item in self.rat_types:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ratTypes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in qos_param_sets (list)
        _items = []
        if self.qos_param_sets:
            for _item in self.qos_param_sets:
                if _item:
                    _items.append(_item.to_dict())
            _dict['qosParamSets'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of QosPolicyAssistReq from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "orderCriterion": QosPolOrderCriterion.from_dict(obj.get("orderCriterion")) if obj.get("orderCriterion") is not None else None,
            "orderDirection": MatchingDirection.from_dict(obj.get("orderDirection")) if obj.get("orderDirection") is not None else None,
            "freqs": obj.get("freqs"),
            "ratTypes": [RatType.from_dict(_item) for _item in obj.get("ratTypes")] if obj.get("ratTypes") is not None else None,
            "qosParamSets": [QosPara.from_dict(_item) for _item in obj.get("qosParamSets")] if obj.get("qosParamSets") is not None else None,
            "requestedQoe": obj.get("requestedQoe")
        })
        return _obj


