# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nncof.models.matching_direction import MatchingDirection
from nncof.models.rat_type import RatType
from nncof.models.threshold_level import ThresholdLevel
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RatFreqInformation(BaseModel):
    """
    Represents the RAT type and/or Frequency information.
    """ # noqa: E501
    all_freq: Optional[StrictBool] = Field(default=None, description="Set to \"true\" to indicate to handle all the frequencies the NCOF received, otherwise set to \"false\" or omit. The \"allFreq\" attribute and the \"freq\" attribute are mutually exclusive. ", alias="allFreq")
    all_rat: Optional[StrictBool] = Field(default=None, description="Set to \"true\" to indicate to handle all the RAT Types the NCOF received, otherwise set to \"false\" or omit. The \"allRat\" attribute and the \"ratType\" attribute are mutually exclusive. ", alias="allRat")
    freq: Optional[Annotated[int, Field(le=3279165, strict=True, ge=0)]] = Field(default=None, description="Integer value indicating the ARFCN applicable for a downlink, uplink or bi-directional (TDD) NR global frequency raster, as definition of \"ARFCN-ValueNR\" IE in clause 6.3.2 of 3GPP TS 38.331. ")
    rat_type: Optional[RatType] = Field(default=None, alias="ratType")
    svc_exp_threshold: Optional[ThresholdLevel] = Field(default=None, alias="svcExpThreshold")
    matching_dir: Optional[MatchingDirection] = Field(default=None, alias="matchingDir")
    __properties: ClassVar[List[str]] = ["allFreq", "allRat", "freq", "ratType", "svcExpThreshold", "matchingDir"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RatFreqInformation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of rat_type
        if self.rat_type:
            _dict['ratType'] = self.rat_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of svc_exp_threshold
        if self.svc_exp_threshold:
            _dict['svcExpThreshold'] = self.svc_exp_threshold.to_dict()
        # override the default output from pydantic by calling `to_dict()` of matching_dir
        if self.matching_dir:
            _dict['matchingDir'] = self.matching_dir.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RatFreqInformation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allFreq": obj.get("allFreq"),
            "allRat": obj.get("allRat"),
            "freq": obj.get("freq"),
            "ratType": RatType.from_dict(obj.get("ratType")) if obj.get("ratType") is not None else None,
            "svcExpThreshold": ThresholdLevel.from_dict(obj.get("svcExpThreshold")) if obj.get("svcExpThreshold") is not None else None,
            "matchingDir": MatchingDirection.from_dict(obj.get("matchingDir")) if obj.get("matchingDir") is not None else None
        })
        return _obj


