# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nncof.models.geographical_area import GeographicalArea
from nncof.models.plmn_id_nid import PlmnIdNid
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RoamingInfo(BaseModel):
    """
    Information related to roaming analytics.
    """ # noqa: E501
    plmn_id: Optional[PlmnIdNid] = Field(default=None, alias="plmnId")
    aois: Optional[Annotated[List[GeographicalArea], Field(min_length=1)]] = Field(default=None, description="Areas of Interest in the HPLMN or the VPLMN.")
    serving_nf_ids: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, description="NF ID(s) of the NF(s) serving the roaming UE(s) in the VPLMN.", alias="servingNfIds")
    serving_nf_set_ids: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, description="NF Set ID(s) of the NF Set(s) serving the roaming UE(s) in the VPLMN.", alias="servingNfSetIds")
    __properties: ClassVar[List[str]] = ["plmnId", "aois", "servingNfIds", "servingNfSetIds"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RoamingInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of plmn_id
        if self.plmn_id:
            _dict['plmnId'] = self.plmn_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in aois (list)
        _items = []
        if self.aois:
            for _item in self.aois:
                if _item:
                    _items.append(_item.to_dict())
            _dict['aois'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RoamingInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "plmnId": PlmnIdNid.from_dict(obj.get("plmnId")) if obj.get("plmnId") is not None else None,
            "aois": [GeographicalArea.from_dict(_item) for _item in obj.get("aois")] if obj.get("aois") is not None else None,
            "servingNfIds": obj.get("servingNfIds"),
            "servingNfSetIds": obj.get("servingNfSetIds")
        })
        return _obj


