# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nncof.models.addr_fqdn import AddrFqdn
from nncof.models.location_info import LocationInfo
from nncof.models.network_area_info import NetworkAreaInfo
from nncof.models.pdu_session_info import PduSessionInfo
from nncof.models.rat_freq_information import RatFreqInformation
from nncof.models.service_experience_type import ServiceExperienceType
from nncof.models.snssai import Snssai
from nncof.models.svc_experience import SvcExperience
from nncof.models.upf_information import UpfInformation
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ServiceExperienceInfo(BaseModel):
    """
    Represents service experience information.
    """ # noqa: E501
    svc_exprc: SvcExperience = Field(alias="svcExprc")
    svc_exprc_variance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="string with format 'float' as defined in OpenAPI.", alias="svcExprcVariance")
    supis: Optional[Annotated[List[Annotated[str, Field(strict=True)]], Field(min_length=1)]] = None
    snssai: Optional[Snssai] = None
    app_id: Optional[StrictStr] = Field(default=None, description="String providing an application identifier.", alias="appId")
    srv_expc_type: Optional[ServiceExperienceType] = Field(default=None, alias="srvExpcType")
    ue_locs: Optional[Annotated[List[LocationInfo], Field(min_length=1)]] = Field(default=None, alias="ueLocs")
    upf_info: Optional[UpfInformation] = Field(default=None, alias="upfInfo")
    dnai: Optional[StrictStr] = Field(default=None, description="DNAI (Data network access identifier), see clause 5.6.7 of 3GPP TS 23.501.")
    app_server_inst: Optional[AddrFqdn] = Field(default=None, alias="appServerInst")
    confidence: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.")
    dnn: Optional[StrictStr] = Field(default=None, description="String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \"Label1.Label2.Label3\"). ")
    network_area: Optional[NetworkAreaInfo] = Field(default=None, alias="networkArea")
    nsi_id: Optional[StrictStr] = Field(default=None, description="Contains the Identifier of the selected Network Slice instance", alias="nsiId")
    ratio: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=None, description="Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.  ")
    rat_freq: Optional[RatFreqInformation] = Field(default=None, alias="ratFreq")
    pdu_ses_info: Optional[PduSessionInfo] = Field(default=None, alias="pduSesInfo")
    __properties: ClassVar[List[str]] = ["svcExprc", "svcExprcVariance", "supis", "snssai", "appId", "srvExpcType", "ueLocs", "upfInfo", "dnai", "appServerInst", "confidence", "dnn", "networkArea", "nsiId", "ratio", "ratFreq", "pduSesInfo"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ServiceExperienceInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of svc_exprc
        if self.svc_exprc:
            _dict['svcExprc'] = self.svc_exprc.to_dict()
        # override the default output from pydantic by calling `to_dict()` of snssai
        if self.snssai:
            _dict['snssai'] = self.snssai.to_dict()
        # override the default output from pydantic by calling `to_dict()` of srv_expc_type
        if self.srv_expc_type:
            _dict['srvExpcType'] = self.srv_expc_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in ue_locs (list)
        _items = []
        if self.ue_locs:
            for _item in self.ue_locs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ueLocs'] = _items
        # override the default output from pydantic by calling `to_dict()` of upf_info
        if self.upf_info:
            _dict['upfInfo'] = self.upf_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of app_server_inst
        if self.app_server_inst:
            _dict['appServerInst'] = self.app_server_inst.to_dict()
        # override the default output from pydantic by calling `to_dict()` of network_area
        if self.network_area:
            _dict['networkArea'] = self.network_area.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rat_freq
        if self.rat_freq:
            _dict['ratFreq'] = self.rat_freq.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pdu_ses_info
        if self.pdu_ses_info:
            _dict['pduSesInfo'] = self.pdu_ses_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ServiceExperienceInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "svcExprc": SvcExperience.from_dict(obj.get("svcExprc")) if obj.get("svcExprc") is not None else None,
            "svcExprcVariance": obj.get("svcExprcVariance"),
            "supis": obj.get("supis"),
            "snssai": Snssai.from_dict(obj.get("snssai")) if obj.get("snssai") is not None else None,
            "appId": obj.get("appId"),
            "srvExpcType": ServiceExperienceType.from_dict(obj.get("srvExpcType")) if obj.get("srvExpcType") is not None else None,
            "ueLocs": [LocationInfo.from_dict(_item) for _item in obj.get("ueLocs")] if obj.get("ueLocs") is not None else None,
            "upfInfo": UpfInformation.from_dict(obj.get("upfInfo")) if obj.get("upfInfo") is not None else None,
            "dnai": obj.get("dnai"),
            "appServerInst": AddrFqdn.from_dict(obj.get("appServerInst")) if obj.get("appServerInst") is not None else None,
            "confidence": obj.get("confidence"),
            "dnn": obj.get("dnn"),
            "networkArea": NetworkAreaInfo.from_dict(obj.get("networkArea")) if obj.get("networkArea") is not None else None,
            "nsiId": obj.get("nsiId"),
            "ratio": obj.get("ratio"),
            "ratFreq": RatFreqInformation.from_dict(obj.get("ratFreq")) if obj.get("ratFreq") is not None else None,
            "pduSesInfo": PduSessionInfo.from_dict(obj.get("pduSesInfo")) if obj.get("pduSesInfo") is not None else None
        })
        return _obj


