# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nncof.models.analytics_context_identifier import AnalyticsContextIdentifier
from nncof.models.model_info import ModelInfo
from nncof.models.nncof_events_subscription import NncofEventsSubscription
from nncof.models.transfer_request_type import TransferRequestType
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SubscriptionTransferInfo(BaseModel):
    """
    Contains information about subscriptions that are requested to be transferred.
    """ # noqa: E501
    trans_req_type: TransferRequestType = Field(alias="transReqType")
    ncof_ev_sub: NncofEventsSubscription = Field(alias="ncofEvSub")
    consumer_id: StrictStr = Field(description="String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4.  ", alias="consumerId")
    context_id: Optional[AnalyticsContextIdentifier] = Field(default=None, alias="contextId")
    source_nf_ids: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, alias="sourceNfIds")
    source_set_ids: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, alias="sourceSetIds")
    model_info: Optional[Annotated[List[ModelInfo], Field(min_length=1)]] = Field(default=None, alias="modelInfo")
    __properties: ClassVar[List[str]] = ["transReqType", "ncofEvSub", "consumerId", "contextId", "sourceNfIds", "sourceSetIds", "modelInfo"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SubscriptionTransferInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of trans_req_type
        if self.trans_req_type:
            _dict['transReqType'] = self.trans_req_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ncof_ev_sub
        if self.ncof_ev_sub:
            _dict['ncofEvSub'] = self.ncof_ev_sub.to_dict()
        # override the default output from pydantic by calling `to_dict()` of context_id
        if self.context_id:
            _dict['contextId'] = self.context_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in model_info (list)
        _items = []
        if self.model_info:
            for _item in self.model_info:
                if _item:
                    _items.append(_item.to_dict())
            _dict['modelInfo'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SubscriptionTransferInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "transReqType": TransferRequestType.from_dict(obj.get("transReqType")) if obj.get("transReqType") is not None else None,
            "ncofEvSub": NncofEventsSubscription.from_dict(obj.get("ncofEvSub")) if obj.get("ncofEvSub") is not None else None,
            "consumerId": obj.get("consumerId"),
            "contextId": AnalyticsContextIdentifier.from_dict(obj.get("contextId")) if obj.get("contextId") is not None else None,
            "sourceNfIds": obj.get("sourceNfIds"),
            "sourceSetIds": obj.get("sourceSetIds"),
            "modelInfo": [ModelInfo.from_dict(_item) for _item in obj.get("modelInfo")] if obj.get("modelInfo") is not None else None
        })
        return _obj


