# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nncof.models.matching_direction import MatchingDirection
from nncof.models.wlan_ordering_criterion import WlanOrderingCriterion
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WlanPerformanceReq(BaseModel):
    """
    Represents other WLAN performance analytics requirements.
    """ # noqa: E501
    ss_ids: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, alias="ssIds")
    bss_ids: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, alias="bssIds")
    wlan_order_criter: Optional[WlanOrderingCriterion] = Field(default=None, alias="wlanOrderCriter")
    order: Optional[MatchingDirection] = None
    __properties: ClassVar[List[str]] = ["ssIds", "bssIds", "wlanOrderCriter", "order"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WlanPerformanceReq from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of wlan_order_criter
        if self.wlan_order_criter:
            _dict['wlanOrderCriter'] = self.wlan_order_criter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of order
        if self.order:
            _dict['order'] = self.order.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WlanPerformanceReq from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ssIds": obj.get("ssIds"),
            "bssIds": obj.get("bssIds"),
            "wlanOrderCriter": WlanOrderingCriterion.from_dict(obj.get("wlanOrderCriter")) if obj.get("wlanOrderCriter") is not None else None,
            "order": MatchingDirection.from_dict(obj.get("order")) if obj.get("order") is not None else None
        })
        return _obj


