# coding: utf-8

"""
    Nsmf_EventExposure

    Session Management Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nsmf.models.af_result_info import AfResultInfo
from nsmf.models.route_information import RouteInformation
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AckOfNotify(BaseModel):
    """
    Represents an acknowledgement information of an event notification.
    """ # noqa: E501
    notif_id: StrictStr = Field(alias="notifId")
    ack_result: AfResultInfo = Field(alias="ackResult")
    supi: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \"lower-with-hyphen\" naming convention    defined in 3GPP TS 29.501. ")
    gpsi: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.  ")
    remote_ims_address: Optional[RouteInformation] = Field(default=None, alias="remoteImsAddress")
    __properties: ClassVar[List[str]] = ["notifId", "ackResult", "supi", "gpsi", "remoteImsAddress"]

    @field_validator('supi')
    def supi_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(imsi-[0-9]{5,15}|nai-.+|gci-.+|gli-.+|.+)$", value):
            raise ValueError(r"must validate the regular expression /^(imsi-[0-9]{5,15}|nai-.+|gci-.+|gli-.+|.+)$/")
        return value

    @field_validator('gpsi')
    def gpsi_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(msisdn-[0-9]{5,15}|extid-[^@]+@[^@]+|.+)$", value):
            raise ValueError(r"must validate the regular expression /^(msisdn-[0-9]{5,15}|extid-[^@]+@[^@]+|.+)$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AckOfNotify from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ack_result
        if self.ack_result:
            _dict['ackResult'] = self.ack_result.to_dict()
        # override the default output from pydantic by calling `to_dict()` of remote_ims_address
        if self.remote_ims_address:
            _dict['remoteImsAddress'] = self.remote_ims_address.to_dict()
        # set to None if remote_ims_address (nullable) is None
        # and model_fields_set contains the field
        if self.remote_ims_address is None and "remote_ims_address" in self.model_fields_set:
            _dict['remoteImsAddress'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AckOfNotify from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "notifId": obj.get("notifId"),
            "ackResult": AfResultInfo.from_dict(obj.get("ackResult")) if obj.get("ackResult") is not None else None,
            "supi": obj.get("supi"),
            "gpsi": obj.get("gpsi"),
            "remoteImsAddress": RouteInformation.from_dict(obj.get("remoteImsAddress")) if obj.get("remoteImsAddress") is not None else None
        })
        return _obj


