# coding: utf-8

"""
    Nsmf_EventExposure

    Session Management Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MpxMediaInfo(BaseModel):
    """
    Contains the Multiplexed Media Identification Information.
    """ # noqa: E501
    ssrc_id: Optional[Annotated[int, Field(le=4294967295, strict=True, ge=0)]] = Field(default=None, description="Integer where the allowed values correspond to the value range of an unsigned 32-bit integer. ", alias="ssrcId")
    payload_type: Optional[Annotated[int, Field(le=127, strict=True, ge=0)]] = Field(default=None, alias="payloadType")
    identification_tag: Optional[StrictStr] = Field(default=None, alias="identificationTag")
    rtp_sdes_hdr_ext_id: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.", alias="rtpSdesHdrExtId")
    rtcp_packet_type: Optional[Annotated[int, Field(le=255, strict=True, ge=0)]] = Field(default=None, alias="rtcpPacketType")
    __properties: ClassVar[List[str]] = ["ssrcId", "payloadType", "identificationTag", "rtpSdesHdrExtId", "rtcpPacketType"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MpxMediaInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MpxMediaInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ssrcId": obj.get("ssrcId"),
            "payloadType": obj.get("payloadType"),
            "identificationTag": obj.get("identificationTag"),
            "rtpSdesHdrExtId": obj.get("rtpSdesHdrExtId"),
            "rtcpPacketType": obj.get("rtcpPacketType")
        })
        return _obj


