# coding: utf-8

"""
    Nsmf_EventExposure

    Session Management Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional, Union
from nsmf.models.buffered_notifications_action import BufferedNotificationsAction
from nsmf.models.subscription_action import SubscriptionAction
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MutingExceptionInstructions(BaseModel):
    """
    Indicates to an Event producer NF instructions for the subscription and stored events when an exception (e.g. full buffer) occurs at the Event producer NF while the event is muted. 
    """ # noqa: E501
    buffered_notifs: Optional[BufferedNotificationsAction] = Field(default=None, alias="bufferedNotifs")
    subscription: Optional[SubscriptionAction] = None
    __properties: ClassVar[List[str]] = ["bufferedNotifs", "subscription"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MutingExceptionInstructions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of buffered_notifs
        if self.buffered_notifs:
            _dict['bufferedNotifs'] = self.buffered_notifs.to_dict()
        # override the default output from pydantic by calling `to_dict()` of subscription
        if self.subscription:
            _dict['subscription'] = self.subscription.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MutingExceptionInstructions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bufferedNotifs": BufferedNotificationsAction.from_dict(obj.get("bufferedNotifs")) if obj.get("bufferedNotifs") is not None else None,
            "subscription": SubscriptionAction.from_dict(obj.get("subscription")) if obj.get("subscription") is not None else None
        })
        return _obj


