# coding: utf-8

"""
    Nsmf_EventExposure

    Session Management Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nsmf.models.nf_heartbeat_info import NfHeartbeatInfo
from nsmf.models.nf_signalling_info_per_time_window import NfSignallingInfoPerTimeWindow
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NfSignallingInfo(BaseModel):
    """
    NF Signalling Information
    """ # noqa: E501
    nf_sig_info_per_wndw: Optional[Annotated[List[NfSignallingInfoPerTimeWindow], Field(min_length=1)]] = Field(default=None, alias="nfSigInfoPerWndw")
    avg_req_proc_time: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.", alias="avgReqProcTime")
    nf_heartbeat_info: Optional[NfHeartbeatInfo] = Field(default=None, alias="nfHeartbeatInfo")
    unexp_status_ind: Optional[StrictBool] = Field(default=False, alias="unexpStatusInd")
    __properties: ClassVar[List[str]] = ["nfSigInfoPerWndw", "avgReqProcTime", "nfHeartbeatInfo", "unexpStatusInd"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NfSignallingInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in nf_sig_info_per_wndw (list)
        _items = []
        if self.nf_sig_info_per_wndw:
            for _item in self.nf_sig_info_per_wndw:
                if _item:
                    _items.append(_item.to_dict())
            _dict['nfSigInfoPerWndw'] = _items
        # override the default output from pydantic by calling `to_dict()` of nf_heartbeat_info
        if self.nf_heartbeat_info:
            _dict['nfHeartbeatInfo'] = self.nf_heartbeat_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NfSignallingInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nfSigInfoPerWndw": [NfSignallingInfoPerTimeWindow.from_dict(_item) for _item in obj.get("nfSigInfoPerWndw")] if obj.get("nfSigInfoPerWndw") is not None else None,
            "avgReqProcTime": obj.get("avgReqProcTime"),
            "nfHeartbeatInfo": NfHeartbeatInfo.from_dict(obj.get("nfHeartbeatInfo")) if obj.get("nfHeartbeatInfo") is not None else None,
            "unexpStatusInd": obj.get("unexpStatusInd") if obj.get("unexpStatusInd") is not None else False
        })
        return _obj


