# coding: utf-8

"""
    Nsmf_EventExposure

    Session Management Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from nsmf.models.pdu_session_status import PduSessionStatus
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PduSessionInfo(BaseModel):
    """
    Represents session information.
    """ # noqa: E501
    n4_sess_id: Optional[StrictStr] = Field(default=None, description="The identifier of the N4 session for the reported PDU Session.", alias="n4SessId")
    sess_inactive_timer: Optional[StrictInt] = Field(default=None, description="indicating a time in seconds.", alias="sessInactiveTimer")
    pdu_sess_status: Optional[PduSessionStatus] = Field(default=None, alias="pduSessStatus")
    __properties: ClassVar[List[str]] = ["n4SessId", "sessInactiveTimer", "pduSessStatus"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PduSessionInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pdu_sess_status
        if self.pdu_sess_status:
            _dict['pduSessStatus'] = self.pdu_sess_status.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PduSessionInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "n4SessId": obj.get("n4SessId"),
            "sessInactiveTimer": obj.get("sessInactiveTimer"),
            "pduSessStatus": PduSessionStatus.from_dict(obj.get("pduSessStatus")) if obj.get("pduSessStatus") is not None else None
        })
        return _obj


