# coding: utf-8

"""
    Nsmf_EventExposure

    Session Management Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nsmf.models.valid_time_period import ValidTimePeriod
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RecurTime(BaseModel):
    """
    Contains the recurring time period
    """ # noqa: E501
    recur_time_window: Optional[ValidTimePeriod] = Field(default=None, alias="recurTimeWindow")
    recur_type: Optional[StrictStr] = Field(default=None, description="Indicates the recurrence applicable to a time window.", alias="recurType")
    recur_month: Optional[Annotated[List[Annotated[int, Field(le=12, strict=True, ge=1)]], Field(min_length=1)]] = Field(default=None, alias="recurMonth")
    recur_week: Optional[Annotated[List[Annotated[int, Field(le=64, strict=True, ge=1)]], Field(min_length=1)]] = Field(default=None, alias="recurWeek")
    recur_day: Optional[Annotated[List[Annotated[int, Field(le=7, strict=True, ge=1)]], Field(min_length=1)]] = Field(default=None, alias="recurDay")
    recur_date: Optional[Annotated[List[datetime], Field(min_length=1)]] = Field(default=None, alias="recurDate")
    recur_end_time: Optional[datetime] = Field(default=None, description="string with format \"date-time\" as defined in OpenAPI.", alias="recurEndTime")
    __properties: ClassVar[List[str]] = ["recurTimeWindow", "recurType", "recurMonth", "recurWeek", "recurDay", "recurDate", "recurEndTime"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RecurTime from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of recur_time_window
        if self.recur_time_window:
            _dict['recurTimeWindow'] = self.recur_time_window.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RecurTime from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "recurTimeWindow": ValidTimePeriod.from_dict(obj.get("recurTimeWindow")) if obj.get("recurTimeWindow") is not None else None,
            "recurType": obj.get("recurType"),
            "recurMonth": obj.get("recurMonth"),
            "recurWeek": obj.get("recurWeek"),
            "recurDay": obj.get("recurDay"),
            "recurDate": obj.get("recurDate"),
            "recurEndTime": obj.get("recurEndTime")
        })
        return _obj


