# coding: utf-8

"""
    Nsmf_EventExposure

    Session Management Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ThroughputMeasurement(BaseModel):
    """
    Throughput Measurement information
    """ # noqa: E501
    ul_throughput: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ", alias="ulThroughput")
    dl_throughput: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". ", alias="dlThroughput")
    ul_packet_throughput: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing a packet rate, i.e., packet per second; the prefixes follow the symbols from The International System of Units, and represent x1000 multipliers. ", alias="ulPacketThroughput")
    dl_packet_throughput: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String representing a packet rate, i.e., packet per second; the prefixes follow the symbols from The International System of Units, and represent x1000 multipliers. ", alias="dlPacketThroughput")
    __properties: ClassVar[List[str]] = ["ulThroughput", "dlThroughput", "ulPacketThroughput", "dlPacketThroughput"]

    @field_validator('ul_throughput')
    def ul_throughput_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$/")
        return value

    @field_validator('dl_throughput')
    def dl_throughput_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$/")
        return value

    @field_validator('ul_packet_throughput')
    def ul_packet_throughput_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)? (pps|kpps|Mpps|Gpps|Tpps)$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)? (pps|kpps|Mpps|Gpps|Tpps)$/")
        return value

    @field_validator('dl_packet_throughput')
    def dl_packet_throughput_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^\d+(\.\d+)? (pps|kpps|Mpps|Gpps|Tpps)$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)? (pps|kpps|Mpps|Gpps|Tpps)$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ThroughputMeasurement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ThroughputMeasurement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ulThroughput": obj.get("ulThroughput"),
            "dlThroughput": obj.get("dlThroughput"),
            "ulPacketThroughput": obj.get("ulPacketThroughput"),
            "dlPacketThroughput": obj.get("dlPacketThroughput")
        })
        return _obj


