# coding: utf-8

"""
    Nsmf_EventExposure

    Session Management Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

    The version of the OpenAPI document: 1.4.0-alpha.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from nsmf.models.eth_flow_description import EthFlowDescription
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TraffRouteReqOutcome(BaseModel):
    """
    Represents the installation outcome of the requested traffic routing requirements. 
    """ # noqa: E501
    succ_traffic_flows: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, alias="succTrafficFlows")
    succ_eth_traffic_flows: Optional[Annotated[List[EthFlowDescription], Field(min_length=1)]] = Field(default=None, alias="succEthTrafficFlows")
    failed_traffic_flows: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, alias="failedTrafficFlows")
    failed_eth_traffic_flows: Optional[Annotated[List[EthFlowDescription], Field(min_length=1)]] = Field(default=None, alias="failedEthTrafficFlows")
    __properties: ClassVar[List[str]] = ["succTrafficFlows", "succEthTrafficFlows", "failedTrafficFlows", "failedEthTrafficFlows"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TraffRouteReqOutcome from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in succ_eth_traffic_flows (list)
        _items = []
        if self.succ_eth_traffic_flows:
            for _item in self.succ_eth_traffic_flows:
                if _item:
                    _items.append(_item.to_dict())
            _dict['succEthTrafficFlows'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in failed_eth_traffic_flows (list)
        _items = []
        if self.failed_eth_traffic_flows:
            for _item in self.failed_eth_traffic_flows:
                if _item:
                    _items.append(_item.to_dict())
            _dict['failedEthTrafficFlows'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TraffRouteReqOutcome from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "succTrafficFlows": obj.get("succTrafficFlows"),
            "succEthTrafficFlows": [EthFlowDescription.from_dict(_item) for _item in obj.get("succEthTrafficFlows")] if obj.get("succEthTrafficFlows") is not None else None,
            "failedTrafficFlows": obj.get("failedTrafficFlows"),
            "failedEthTrafficFlows": [EthFlowDescription.from_dict(_item) for _item in obj.get("failedEthTrafficFlows")] if obj.get("failedEthTrafficFlows") is not None else None
        })
        return _obj


