# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AnalyticsFeedbackInfo(BaseModel):
    """
    Analytics feedback information.
    """ # noqa: E501
    action_times: Annotated[List[datetime], Field(min_length=1)] = Field(description="The times at which an action was taken.", alias="actionTimes")
    used_ana_types: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, description="The analytics types that were used to take the action.", alias="usedAnaTypes")
    impact_ind: Optional[StrictBool] = Field(default=None, description="Indication about the impact of an action on the ground truth data.", alias="impactInd")
    __properties: ClassVar[List[str]] = ["actionTimes", "usedAnaTypes", "impactInd"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AnalyticsFeedbackInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AnalyticsFeedbackInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "actionTimes": obj.get("actionTimes"),
            "usedAnaTypes": obj.get("usedAnaTypes"),
            "impactInd": obj.get("impactInd")
        })
        return _obj


