# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CellPowerCtrlOptReq(BaseModel):
    """
    The cell power control and optimization requirement information.
    """ # noqa: E501
    order_criterion: Optional[StrictStr] = Field(default=None, description="Possible values are:    - QOE: Indicates the order is the QoE.   - USAGE_DURATION: Indicates the order is the QoS Flow Usage Duration.   - NUMBER_OF_USAGES: Indicates the order is the number of usages of the QoS Flow.", alias="_orderCriterion")
    order_direction: Optional[StrictStr] = Field(default=None, description="Represents the matching direction when crossing a threshold.   Possible values are: - ASCENDING: Threshold is crossed in ascending direction. - DESCENDING: Threshold is crossed in descending direction. - CROSSED: Threshold is crossed either in ascending or descending direction. ", alias="_orderDirection")
    freqs: Optional[Annotated[List[Annotated[int, Field(le=3279165, strict=True, ge=0)]], Field(min_length=1)]] = None
    rat_types: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, alias="_ratTypes")
    __properties: ClassVar[List[str]] = ["_orderCriterion", "_orderDirection", "freqs", "_ratTypes"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CellPowerCtrlOptReq from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CellPowerCtrlOptReq from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_orderCriterion": obj.get("_orderCriterion"),
            "_orderDirection": obj.get("_orderDirection"),
            "freqs": obj.get("freqs"),
            "_ratTypes": obj.get("_ratTypes")
        })
        return _obj


