# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nncof.models.network_area_info import NetworkAreaInfo
from nncof.models.time_window import TimeWindow
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class E2eDataVolTransTimeUeList(BaseModel):
    """
    Contains the list of UEs classified based on experience level of E2E Data Volume Transfer  Time  
    """ # noqa: E501
    high_level: Optional[Annotated[List[Annotated[str, Field(strict=True)]], Field(min_length=1)]] = Field(default=None, alias="highLevel")
    medium_level: Optional[Annotated[List[Annotated[str, Field(strict=True)]], Field(min_length=1)]] = Field(default=None, alias="mediumLevel")
    low_level: Optional[Annotated[List[Annotated[str, Field(strict=True)]], Field(min_length=1)]] = Field(default=None, alias="lowLevel")
    low_ratio: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=None, description="Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.  ", alias="lowRatio")
    medium_ratio: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=None, description="Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.  ", alias="mediumRatio")
    high_ratio: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=None, description="Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.  ", alias="highRatio")
    spatial_validity: Optional[NetworkAreaInfo] = Field(default=None, alias="spatialValidity")
    validity_period: Optional[TimeWindow] = Field(default=None, alias="validityPeriod")
    __properties: ClassVar[List[str]] = ["highLevel", "mediumLevel", "lowLevel", "lowRatio", "mediumRatio", "highRatio", "spatialValidity", "validityPeriod"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of E2eDataVolTransTimeUeList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of spatial_validity
        if self.spatial_validity:
            _dict['spatialValidity'] = self.spatial_validity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of validity_period
        if self.validity_period:
            _dict['validityPeriod'] = self.validity_period.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of E2eDataVolTransTimeUeList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "highLevel": obj.get("highLevel"),
            "mediumLevel": obj.get("mediumLevel"),
            "lowLevel": obj.get("lowLevel"),
            "lowRatio": obj.get("lowRatio"),
            "mediumRatio": obj.get("mediumRatio"),
            "highRatio": obj.get("highRatio"),
            "spatialValidity": NetworkAreaInfo.from_dict(obj.get("spatialValidity")) if obj.get("spatialValidity") is not None else None,
            "validityPeriod": TimeWindow.from_dict(obj.get("validityPeriod")) if obj.get("validityPeriod") is not None else None
        })
        return _obj


