# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RadialVelocity(BaseModel):
    """
    Rate of change of a range.
    """ # noqa: E501
    units_radial_velocity: StrictStr = Field(description="The the units of linear velocity.", alias="unitsRadialVelocity")
    radial_velocity: Annotated[int, Field(le=2047, strict=True, ge=-2048)] = Field(description="Indicates value of rate of change of a range between the device A and device B.", alias="radialVelocity")
    r_velocity_uncertainty: Annotated[int, Field(le=255, strict=True, ge=0)] = Field(description="Indicates uncertainty for rate of change of an range.", alias="rVelocityUncertainty")
    __properties: ClassVar[List[str]] = ["unitsRadialVelocity", "radialVelocity", "rVelocityUncertainty"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RadialVelocity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RadialVelocity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "unitsRadialVelocity": obj.get("unitsRadialVelocity"),
            "radialVelocity": obj.get("radialVelocity"),
            "rVelocityUncertainty": obj.get("rVelocityUncertainty")
        })
        return _obj


