# coding: utf-8

"""
    Nncof_EventsSubscription

    NCOF Event Exposure Service for 6G-I2P PoC Scenario.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from nncof.models.angular_velocity import AngularVelocity
from nncof.models.radial_velocity import RadialVelocity
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RelativeVelocityWithUncertainty(BaseModel):
    """
    Relative velocity with radial velocity and transverse velocity.
    """ # noqa: E501
    r_velocity: Optional[RadialVelocity] = Field(default=None, alias="rVelocity")
    a_transverse_velocity: Optional[AngularVelocity] = Field(default=None, alias="aTransverseVelocity")
    e_transverse_velocity: Optional[AngularVelocity] = Field(default=None, alias="eTransverseVelocity")
    __properties: ClassVar[List[str]] = ["rVelocity", "aTransverseVelocity", "eTransverseVelocity"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RelativeVelocityWithUncertainty from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of r_velocity
        if self.r_velocity:
            _dict['rVelocity'] = self.r_velocity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of a_transverse_velocity
        if self.a_transverse_velocity:
            _dict['aTransverseVelocity'] = self.a_transverse_velocity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of e_transverse_velocity
        if self.e_transverse_velocity:
            _dict['eTransverseVelocity'] = self.e_transverse_velocity.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RelativeVelocityWithUncertainty from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rVelocity": RadialVelocity.from_dict(obj.get("rVelocity")) if obj.get("rVelocity") is not None else None,
            "aTransverseVelocity": AngularVelocity.from_dict(obj.get("aTransverseVelocity")) if obj.get("aTransverseVelocity") is not None else None,
            "eTransverseVelocity": AngularVelocity.from_dict(obj.get("eTransverseVelocity")) if obj.get("eTransverseVelocity") is not None else None
        })
        return _obj


