# coding: utf-8

"""
    Nncof_EventsSubscriptionNotification (Callback Receiver)

    Callback receiver specification for the Nncof_EventsSubscription service.  This spec is consumed by PCF/RICF (the NF service consumer) that subscribes to NCOF events. The consumer must implement an HTTP server that exposes the endpoint defined here so that NCOF can deliver notifications to it.  It is intentionally extracted from `Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml` because OpenAPI Generator does not generate server stubs for the `callbacks:` section of an OpenAPI document. Generating from this standalone spec yields a ready-to-implement FastAPI server stub on the consumer side.  Schema simplifications applied for code-generator compatibility (the original `Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml` is unchanged):   - `oneOf` constraints are dropped (validation deferred to business logic).   - 3GPP forward-compatible enum pattern (`anyOf: [enum-string, free-string]`)     is flattened to plain `type: string`.   - All cross-file `$ref`s are inlined into this single document.  6G-I2P ETRI-MoDuTec PoC Scenario. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class AccessType(str, Enum):
    """
    Indicates whether the access is  via 3GPP or via non-3GPP.
    """

    """
    allowed enum values
    """
    ENUM_3_GPP_ACCESS = '3GPP_ACCESS'
    NON_3_GPP_ACCESS = 'NON_3GPP_ACCESS'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccessType from a JSON string"""
        return cls(json.loads(json_str))


