# coding: utf-8

"""
    Nncof_EventsSubscriptionNotification (Callback Receiver)

    Callback receiver specification for the Nncof_EventsSubscription service.  This spec is consumed by PCF/RICF (the NF service consumer) that subscribes to NCOF events. The consumer must implement an HTTP server that exposes the endpoint defined here so that NCOF can deliver notifications to it.  It is intentionally extracted from `Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml` because OpenAPI Generator does not generate server stubs for the `callbacks:` section of an OpenAPI document. Generating from this standalone spec yields a ready-to-implement FastAPI server stub on the consumer side.  Schema simplifications applied for code-generator compatibility (the original `Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml` is unchanged):   - `oneOf` constraints are dropped (validation deferred to business logic).   - 3GPP forward-compatible enum pattern (`anyOf: [enum-string, free-string]`)     is flattened to plain `type: string`.   - All cross-file `$ref`s are inlined into this single document.  6G-I2P ETRI-MoDuTec PoC Scenario. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from nncof_cb.models.gnb_id import GNbId
from nncof_cb.models.plmn_id import PlmnId
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GlobalRanNodeId(BaseModel):
    """
    One of the six attributes n3IwfId, gNbIdm, ngeNbId, wagfId, tngfId, eNbId shall be present. 
    """ # noqa: E501
    plmn_id: PlmnId = Field(alias="plmnId")
    n3_iwf_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="This represents the identifier of the N3IWF ID as specified in clause 9.3.1.57 of  3GPP TS 38.413 in hexadecimal representation. Each character in the string shall take a value  of \"0\" to \"9\", \"a\" to \"f\" or \"A\" to \"F\" and shall represent 4 bits. The most significant  character representing the 4 most significant bits of the N3IWF ID shall appear first in the  string, and the character representing the 4 least significant bit of the N3IWF ID shall  appear last in the string.  ", alias="n3IwfId")
    g_nb_id: Optional[GNbId] = Field(default=None, alias="gNbId")
    nge_nb_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="This represents the identifier of the ng-eNB ID as specified in clause 9.3.1.8 of  3GPP TS 38.413. The value of the ng-eNB ID shall be encoded in hexadecimal representation.  Each character in the string shall take a value of \"0\" to \"9\", \"a\" to \"f\" or \"A\" to \"F\" and  shall represent 4 bits. The padding 0 shall be added to make multiple nibbles, so the most  significant character representing the padding 0 if required together with the 4 most  significant bits of the ng-eNB ID shall appear first in the string, and the character  representing the 4 least significant bit of the ng-eNB ID (to form a nibble) shall appear last  in the string.  ", alias="ngeNbId")
    wagf_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="This represents the identifier of the W-AGF ID as specified in clause 9.3.1.162 of  3GPP TS 38.413 in hexadecimal representation. Each character in the string shall take a value  of \"0\" to \"9\", \"a\" to \"f\" or \"A\" to \"F\" and shall represent 4 bits. The most significant  character representing the 4 most significant bits of the W-AGF ID shall appear first in the  string, and the character representing the 4 least significant bit of the W-AGF ID shall  appear last in the string.  ", alias="wagfId")
    tngf_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="This represents the identifier of the TNGF ID as specified in clause 9.3.1.161 of  3GPP TS 38.413  in hexadecimal representation. Each character in the string shall take a value of \"0\" to \"9\", \"a\"  to \"f\" or \"A\" to \"F\" and shall represent 4 bits. The most significant character representing the  4 most significant bits of the TNGF ID shall appear first in the string, and the character  representing the 4 least significant bit of the TNGF ID shall appear last in the string.  ", alias="tngfId")
    nid: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="This represents the Network Identifier, which together with a PLMN ID is used to identify an SNPN (see 3GPP TS 23.003 and 3GPP TS 23.501 clause 5.30.2.1).  ")
    e_nb_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="This represents the identifier of the eNB ID as specified in clause 9.2.1.37 of  3GPP TS 36.413. The string shall be formatted with the following pattern  '^('MacroeNB-[A-Fa-f0-9]{5}|LMacroeNB-[A-Fa-f0-9]{6}|SMacroeNB-[A-Fa-f0-9]{5} |HomeeNB-[A-Fa-f0-9]{7})$'. The value of the eNB ID shall be encoded in hexadecimal representation. Each character in the  string shall take a value of \"0\" to \"9\", \"a\" to \"f\" or \"A\" to \"F\" and shall represent 4 bits.  The padding 0 shall be added to make multiple nibbles, so the most significant character  representing the padding 0 if required together with the 4 most significant bits of the eNB ID  shall appear first in the string, and the character representing the 4 least significant bit  of the eNB ID (to form a nibble) shall appear last in the string. ", alias="eNbId")
    __properties: ClassVar[List[str]] = ["plmnId", "n3IwfId", "gNbId", "ngeNbId", "wagfId", "tngfId", "nid", "eNbId"]

    @field_validator('n3_iwf_id')
    def n3_iwf_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Fa-f0-9]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]+$/")
        return value

    @field_validator('nge_nb_id')
    def nge_nb_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(MacroNGeNB-[A-Fa-f0-9]{5}|LMacroNGeNB-[A-Fa-f0-9]{6}|SMacroNGeNB-[A-Fa-f0-9]{5})$", value):
            raise ValueError(r"must validate the regular expression /^(MacroNGeNB-[A-Fa-f0-9]{5}|LMacroNGeNB-[A-Fa-f0-9]{6}|SMacroNGeNB-[A-Fa-f0-9]{5})$/")
        return value

    @field_validator('wagf_id')
    def wagf_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Fa-f0-9]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]+$/")
        return value

    @field_validator('tngf_id')
    def tngf_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Fa-f0-9]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]+$/")
        return value

    @field_validator('nid')
    def nid_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Fa-f0-9]{11}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]{11}$/")
        return value

    @field_validator('e_nb_id')
    def e_nb_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(MacroeNB-[A-Fa-f0-9]{5}|LMacroeNB-[A-Fa-f0-9]{6}|SMacroeNB-[A-Fa-f0-9]{5}|HomeeNB-[A-Fa-f0-9]{7})$", value):
            raise ValueError(r"must validate the regular expression /^(MacroeNB-[A-Fa-f0-9]{5}|LMacroeNB-[A-Fa-f0-9]{6}|SMacroeNB-[A-Fa-f0-9]{5}|HomeeNB-[A-Fa-f0-9]{7})$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GlobalRanNodeId from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of plmn_id
        if self.plmn_id:
            _dict['plmnId'] = self.plmn_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of g_nb_id
        if self.g_nb_id:
            _dict['gNbId'] = self.g_nb_id.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GlobalRanNodeId from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "plmnId": PlmnId.from_dict(obj.get("plmnId")) if obj.get("plmnId") is not None else None,
            "n3IwfId": obj.get("n3IwfId"),
            "gNbId": GNbId.from_dict(obj.get("gNbId")) if obj.get("gNbId") is not None else None,
            "ngeNbId": obj.get("ngeNbId"),
            "wagfId": obj.get("wagfId"),
            "tngfId": obj.get("tngfId"),
            "nid": obj.get("nid"),
            "eNbId": obj.get("eNbId")
        })
        return _obj


