# coding: utf-8

"""
Nnef_EventExposure

NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

The version of the OpenAPI document: 1.4.0-alpha.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from fastapi import FastAPI

from nnef.apis.individual_subscription_document_api import (
    router as IndividualSubscriptionDocumentApiRouter,
)
from nnef.apis.subscriptions_collection_api import (
    router as SubscriptionsCollectionApiRouter,
)
from nnef.apis.ncof_events_subscription_notification_callback_receiver_api import (
    router as NCOFEventsSubscriptionNotificationCallbackReceiverApiRouter,
)

from nnef.impl import utils

app = FastAPI(
    title="Nnef_EventExposure",
    description="NEF Event Exposure Service.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. ",
    version="1.4.0-alpha.4",
)

app.include_router(IndividualSubscriptionDocumentApiRouter)
app.include_router(SubscriptionsCollectionApiRouter)
app.include_router(NCOFEventsSubscriptionNotificationCallbackReceiverApiRouter)
utils.print_logo()
