# coding: utf-8

"""
Nncof_EventsSubscription

NCOF Event Exposure Service for 6G-I2P PoC Scenario.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import logging
import os
from dotenv import load_dotenv

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware

from nncof.apis.individual_ncof_event_subscription_transfer_document_api import (
    router as IndividualNCOFEventSubscriptionTransferDocumentApiRouter,
)
from nncof.apis.individual_ncof_events_subscription_document_api import (
    router as IndividualNCOFEventsSubscriptionDocumentApiRouter,
)
from nncof.apis.ncof_event_subscription_transfers_collection_api import (
    router as NCOFEventSubscriptionTransfersCollectionApiRouter,
)
from nncof.apis.ncof_events_subscriptions_collection_api import (
    router as NCOFEventsSubscriptionsCollectionApiRouter,
)

from nncof.apis.upf_events_notifications_api import (
    router as UPFEventsNotificationApiRouter,
)

from nncof.apis.nef_events_notifications_api import (
    router as NEFEventsNotificationApiRouter,
)

from nncof.apis.web_api import (
    router as WebApiRouter,
)


from nncof.core import utils

load_dotenv()


logger = logging.getLogger(__name__)

title = "Nncof_EventsSubscription"
description = "NCOF Event Exposure Service for 6G-I2P PoC Scenario."
version = "0.1.0"


app = FastAPI(
    title=title,
    description=description,
    version=version,
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # 허용할 출처 리스트
    allow_credentials=True,
    allow_methods=["*"],  # 모든 HTTP 메서드 허용 (GET, POST 등)
    allow_headers=["*"],  # 모든 HTTP 헤더 허용
)
app.include_router(IndividualNCOFEventSubscriptionTransferDocumentApiRouter)
app.include_router(IndividualNCOFEventsSubscriptionDocumentApiRouter)
app.include_router(NCOFEventSubscriptionTransfersCollectionApiRouter)
app.include_router(NCOFEventsSubscriptionsCollectionApiRouter)

app.include_router(UPFEventsNotificationApiRouter)
app.include_router(NEFEventsNotificationApiRouter)
app.include_router(WebApiRouter)

# 정적 파일 서비스 설정
# src/nncof/static 디렉토리를 /static 경로로 마운트합니다.
static_dir = os.path.join(os.path.dirname(__file__), "static")
if not os.path.exists(static_dir):
    os.makedirs(static_dir)

app.mount("/static", StaticFiles(directory=static_dir), name="static")


@app.get("/", include_in_schema=False)
async def read_index():
    index_path = os.path.join(static_dir, "index.html")
    if os.path.exists(index_path):
        return FileResponse(index_path)
    return {"message": "NCOF Event Exposure Service is running. (index.html not found)"}


utils.print_logo(title, description, version)
