"""
Nncof_EventsSubscription

NCOF Event Exposure Service for 6G-I2P PoC Scenario.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import asyncio
import logging
import os
from contextlib import asynccontextmanager, suppress

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from nncof.apis.individual_ncof_event_subscription_transfer_document_api import (
    router as IndividualNCOFEventSubscriptionTransferDocumentApiRouter,
)
from nncof.apis.individual_ncof_events_subscription_document_api import (
    router as IndividualNCOFEventsSubscriptionDocumentApiRouter,
)
from nncof.apis.ncof_event_subscription_transfers_collection_api import (
    router as NCOFEventSubscriptionTransfersCollectionApiRouter,
)
from nncof.apis.ncof_events_subscriptions_collection_api import (
    router as NCOFEventsSubscriptionsCollectionApiRouter,
)
from nncof.apis.nef_events_notifications_api import (
    router as NEFEventsNotificationApiRouter,
)
from nncof.apis.upf_events_notifications_api import (
    router as UPFEventsNotificationApiRouter,
)
from nncof.apis.web_api import (
    router as WebApiRouter,
)
from nncof.core import utils
from nncof.core.lenient_ingest import install_lenient_ingest
from nncof.core.subscription_manager import SubscriptionManager
from nncof.core.utils import system_info

load_dotenv()

info = system_info()

title = info["title"]
description = info["description"]
version = info["version"]


utils.print_logo(title, description, version)


logger = logging.getLogger(__name__)


async def _restore_persisted_subscriptions(manager: SubscriptionManager) -> None:
    """저장 구독 복원을 백그라운드에서 수행하고 실패를 로그로 남긴다.

    태스크 안에서 발생한 예외는 아무도 회수하지 않으면 조용히 사라지므로
    여기서 반드시 로그로 드러낸다.
    """
    try:
        await manager.restore_persisted_subscriptions()
    except asyncio.CancelledError:
        logger.info("저장 구독 복원이 서버 종료로 취소됨")
        raise
    except Exception:
        logger.exception("저장 구독 복원 실패")


@asynccontextmanager
async def lifespan(_: FastAPI):
    """서버 재시작 시 저장 구독을 복원하고 종료 전에 상태를 보존한다."""

    root_logger = logging.getLogger()
    nncof_logger = logging.getLogger(__name__)

    # 공통으로 사용할 Formatter 정의
    formatter = logging.Formatter(
        "[%(asctime)s] [%(levelname)s] [%(name)s] - %(message)s [%(filename)s:%(lineno)d]"
    )

    # 1. Root 로거에 이미 핸들러가 존재하는 경우 -> 기존 핸들러들의 Formatter만 변경
    if root_logger.handlers:
        for handler in root_logger.handlers:
            handler.setFormatter(formatter)

    # 2. Root 및 nncof 로거 모두 핸들러가 없는 경우 -> 핸들러 신규 생성 및 Formatter 설정
    elif not nncof_logger.handlers and not logger.handlers:
        ch = logging.StreamHandler()
        ch.setLevel(logging.INFO)
        ch.setFormatter(formatter)
        root_logger.addHandler(ch)
        root_logger.setLevel(logging.INFO)

    subscription_manager = SubscriptionManager()

    # 저장 구독 복원은 기동을 막지 않도록 백그라운드 태스크로 돌린다.
    # 복원은 구독 1건마다 하위 NF 재구독과 GUI 연출 대기(SubscriptionHandler.start()
    # Phase 2)를 거쳐 약 5초가 걸리고, 응답 없는 NF 를 상대하면 httpx 기본 타임아웃만큼
    # 더 늘어난다. lifespan 안에서 await 하면 hypercorn 기동 타임아웃(기본 60초)에 걸려
    # 구독이 12건쯤 쌓인 상태 파일에서 기동 자체가 실패한다(실측). 그래서 분리한다.
    restore_task = asyncio.create_task(
        _restore_persisted_subscriptions(subscription_manager)
    )
    try:
        yield
    finally:
        # 복원이 끝나기 전에 종료되면 취소하고, shutdown() 의 상태 저장과
        # 순서가 엉키지 않도록 반드시 회수한 뒤 다음으로 넘어간다.
        restore_task.cancel()
        with suppress(asyncio.CancelledError):
            await restore_task
        await subscription_manager.shutdown()


app = FastAPI(
    title=title,
    description=description,
    version=version,
    lifespan=lifespan,
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # 허용할 출처 리스트
    allow_credentials=True,
    allow_methods=["*"],  # 모든 HTTP 메서드 허용 (GET, POST 등)
    allow_headers=["*"],  # 모든 HTTP 헤더 허용
)
app.include_router(IndividualNCOFEventSubscriptionTransferDocumentApiRouter)
app.include_router(IndividualNCOFEventsSubscriptionDocumentApiRouter)
app.include_router(NCOFEventSubscriptionTransfersCollectionApiRouter)
app.include_router(NCOFEventsSubscriptionsCollectionApiRouter)

app.include_router(UPFEventsNotificationApiRouter)
app.include_router(NEFEventsNotificationApiRouter)
app.include_router(WebApiRouter)

# TEMP(두두원 연동 진단) — NCOF_LENIENT_INGEST=1 일 때만 통지 본문을 수리해 통과시킨다.
install_lenient_ingest(app)

# 정적 파일 서비스 설정
# src/nncof/static 디렉토리를 루트(/)로 마운트한다. Vite 빌드 결과물(/assets/*)이 정상 서빙되도록 함.
static_dir = os.path.join(os.path.dirname(__file__), "static")
if not os.path.exists(static_dir):
    os.makedirs(static_dir)

app.mount("/", StaticFiles(directory=static_dir, html=True), name="static")


@app.get("/", include_in_schema=False)
async def read_index():
    index_path = os.path.join(static_dir, "index.html")
    if os.path.exists(index_path):
        return FileResponse(index_path)
    return {"message": "NCOF Event Exposure Service is running. (index.html not found)"}
