# coding: utf-8

"""
Nncof_EventsSubscriptionNotification (Callback Receiver)

Callback receiver specification for the Nncof_EventsSubscription service.  This spec is consumed by PCF/RICF (the NF service consumer) that subscribes to NCOF events. The consumer must implement an HTTP server that exposes the endpoint defined here so that NCOF can deliver notifications to it.  It is intentionally extracted from `Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml` because OpenAPI Generator does not generate server stubs for the `callbacks:` section of an OpenAPI document. Generating from this standalone spec yields a ready-to-implement FastAPI server stub on the consumer side.  Schema simplifications applied for code-generator compatibility (the original `Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml` is unchanged):   - `oneOf` constraints are dropped (validation deferred to business logic).   - 3GPP forward-compatible enum pattern (`anyOf: [enum-string, free-string]`)     is flattened to plain `type: string`.   - All cross-file `$ref`s are inlined into this single document.  6G-I2P ETRI-MoDuTec PoC Scenario.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from fastapi import FastAPI

from nncof_cb.apis.ncof_events_subscription_notification_callback_receiver_api import (
    router as NCOFEventsSubscriptionNotificationCallbackReceiverApiRouter,
)
from nncof_cb.impl import utils

app = FastAPI(
    title="Nncof_EventsSubscriptionNotification (Callback Receiver)",
    description="Callback receiver specification for the Nncof_EventsSubscription service.  This spec is consumed by PCF/RICF (the NF service consumer) that subscribes to NCOF events. The consumer must implement an HTTP server that exposes the endpoint defined here so that NCOF can deliver notifications to it.  It is intentionally extracted from &#x60;Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml&#x60; because OpenAPI Generator does not generate server stubs for the &#x60;callbacks:&#x60; section of an OpenAPI document. Generating from this standalone spec yields a ready-to-implement FastAPI server stub on the consumer side.  Schema simplifications applied for code-generator compatibility (the original &#x60;Nncof_EventsSubscription_PoC_ETRI_DoDo1.yaml&#x60; is unchanged):   - &#x60;oneOf&#x60; constraints are dropped (validation deferred to business logic).   - 3GPP forward-compatible enum pattern (&#x60;anyOf: [enum-string, free-string]&#x60;)     is flattened to plain &#x60;type: string&#x60;.   - All cross-file &#x60;$ref&#x60;s are inlined into this single document.  6G-I2P ETRI-MoDuTec PoC Scenario. ",
    version="0.1.0",
    redirect_slashes=False,
)

app.include_router(NCOFEventsSubscriptionNotificationCallbackReceiverApiRouter)

utils.print_logo()
